import type {
  PlacementItem,
  PlacementItemType,
  TenseDiagnosticArea,
  TenseDifficultyBand,
} from "../types";

type SeedItem = {
  id: string;
  itemType: PlacementItemType;
  difficultyBand: TenseDifficultyBand;
  targetTense: string;
  diagnosticArea: TenseDiagnosticArea;
  prompt: string;
  options: [string, string, string, string];
  correctAnswerId: "a" | "b" | "c" | "d";
  explanation: string;
  teachingImplication: string;
  tags: string[];
};

const difficultyValue: Record<TenseDifficultyBand, number> = {
  easy: 1.35,
  medium: 2.65,
  hard: 4.05,
  advanced: 5.35,
};

const routingIds = new Set([
  "q001",
  "q002",
  "q007",
  "q019",
  "q031",
  "q043",
  "q049",
  "q085",
]);

const optionIds = ["a", "b", "c", "d"] as const;

const seeds: SeedItem[] = [
  { id: "q001", itemType: "contextual-choice", difficultyBand: "easy", targetTense: "present simple", diagnosticArea: "present-tense-control", prompt: "Mona usually ___ coffee before work, but today she is drinking tea.", options: ["drinks", "is drinking", "has drunk", "drank"], correctAnswerId: "a", explanation: "'Usually' shows a routine, so Present Simple is needed.", teachingImplication: "Review Present Simple for habits and routines.", tags: ["present-simple", "habits", "routines"] },
  { id: "q002", itemType: "contextual-choice", difficultyBand: "easy", targetTense: "present continuous", diagnosticArea: "present-tense-control", prompt: "Please be quiet. I ___ to an important message from my manager.", options: ["listen", "listened", "am listening", "have listened"], correctAnswerId: "c", explanation: "The action is happening now, so Present Continuous is needed.", teachingImplication: "Review Present Continuous for actions happening now.", tags: ["present-continuous", "now", "workplace"] },
  { id: "q003", itemType: "dialogue-completion", difficultyBand: "medium", targetTense: "present simple vs present continuous", diagnosticArea: "tense-contrast-control", prompt: "A: What does your brother do?\nB: He ___ as an engineer, but this month he ___ on a training project.", options: ["works / is working", "is working / works", "worked / works", "has worked / worked"], correctAnswerId: "a", explanation: "'Works' describes his regular job; 'is working' describes a temporary situation.", teachingImplication: "Teach permanent vs temporary situations.", tags: ["present-simple", "present-continuous", "temporary-situation"] },
  { id: "q004", itemType: "stative-verb", difficultyBand: "medium", targetTense: "stative verbs", diagnosticArea: "stative-dynamic-control", prompt: "I ___ what you mean now.", options: ["am understanding", "understand", "understood", "have been understanding"], correctAnswerId: "b", explanation: "'Understand' is usually stative, so Present Simple is used.", teachingImplication: "Review stative verbs that do not normally use continuous forms.", tags: ["stative-verbs", "present-simple"] },
  { id: "q005", itemType: "error-correction", difficultyBand: "medium", targetTense: "present continuous error", diagnosticArea: "stative-dynamic-control", prompt: "Choose the correct version. Original: 'I am knowing the answer.'", options: ["I know the answer.", "I am know the answer.", "I have knowing the answer.", "I knew the answer now."], correctAnswerId: "a", explanation: "'Know' is a stative verb and normally uses Present Simple.", teachingImplication: "Review stative verbs: know, believe, understand, prefer.", tags: ["stative-verbs", "correction"] },
  { id: "q006", itemType: "meaning-contrast", difficultyBand: "hard", targetTense: "present simple vs present continuous", diagnosticArea: "tense-contrast-control", prompt: "Which sentence means the situation is temporary?", options: ["I live in Cairo.", "I am living in Cairo while I finish my course.", "I have lived in Cairo since 2010.", "I lived in Cairo when I was young."], correctAnswerId: "b", explanation: "Present Continuous can show a temporary situation around now.", teachingImplication: "Teach Present Continuous for temporary states.", tags: ["present-continuous", "temporary", "meaning"] },
  { id: "q007", itemType: "contextual-choice", difficultyBand: "medium", targetTense: "present perfect", diagnosticArea: "perfect-aspect-control", prompt: "I ___ three online courses this year.", options: ["finished", "have finished", "finish", "was finishing"], correctAnswerId: "b", explanation: "'This year' is an unfinished time period, so Present Perfect is natural.", teachingImplication: "Teach Present Perfect with unfinished time periods.", tags: ["present-perfect", "unfinished-time"] },
  { id: "q008", itemType: "contextual-choice", difficultyBand: "medium", targetTense: "past simple", diagnosticArea: "past-tense-control", prompt: "I ___ three online courses last year.", options: ["have finished", "finish", "finished", "had finished"], correctAnswerId: "c", explanation: "'Last year' is finished time, so Past Simple is needed.", teachingImplication: "Contrast finished and unfinished time.", tags: ["past-simple", "finished-time"] },
  { id: "q009", itemType: "dialogue-completion", difficultyBand: "medium", targetTense: "present perfect experience", diagnosticArea: "perfect-aspect-control", prompt: "A: ___ you ever ___ a presentation in English?\nB: Yes, I did one last month.", options: ["Did / give", "Have / given", "Are / giving", "Had / given"], correctAnswerId: "b", explanation: "'Ever' asks about life experience, so Present Perfect is used.", teachingImplication: "Teach Present Perfect for life experience.", tags: ["present-perfect", "experience"] },
  { id: "q010", itemType: "best-rewrite", difficultyBand: "hard", targetTense: "present perfect vs past simple", diagnosticArea: "perfect-aspect-control", prompt: "Choose the sentence that is closest in meaning: 'I started learning English in 2018, and I still learn it now.'", options: ["I learned English in 2018.", "I have learned English since 2018.", "I had learned English in 2018.", "I was learning English in 2018 only."], correctAnswerId: "b", explanation: "'Since 2018' connects the past to now.", teachingImplication: "Review Present Perfect with since/for.", tags: ["present-perfect", "since", "duration"] },
  { id: "q011", itemType: "error-identification", difficultyBand: "hard", targetTense: "present perfect vs past simple", diagnosticArea: "tense-contrast-control", prompt: "Which sentence is incorrect?", options: ["I have visited London twice.", "I visited London in 2020.", "I have visited London yesterday.", "I have never visited London."], correctAnswerId: "c", explanation: "'Yesterday' is finished time, so Past Simple is needed.", teachingImplication: "Review time markers that require Past Simple.", tags: ["present-perfect-error", "past-simple"] },
  { id: "q012", itemType: "contextual-choice", difficultyBand: "hard", targetTense: "present perfect result", diagnosticArea: "perfect-aspect-control", prompt: "Sarah can't join the meeting because she ___ her laptop charger.", options: ["lost", "has lost", "had lost", "was losing"], correctAnswerId: "b", explanation: "Present Perfect shows a past action with a present result.", teachingImplication: "Teach Present Perfect for present consequences.", tags: ["present-perfect", "present-result"] },
  { id: "q013", itemType: "contextual-choice", difficultyBand: "medium", targetTense: "present perfect continuous", diagnosticArea: "perfect-aspect-control", prompt: "I'm tired because I ___ all morning.", options: ["study", "studied", "have been studying", "had studied"], correctAnswerId: "c", explanation: "The activity started earlier and continued up to now.", teachingImplication: "Teach Present Perfect Continuous for recent ongoing activity.", tags: ["present-perfect-continuous", "duration"] },
  { id: "q014", itemType: "contextual-choice", difficultyBand: "medium", targetTense: "present perfect continuous", diagnosticArea: "perfect-aspect-control", prompt: "How long ___ you ___ for this company?", options: ["do / work", "are / working", "have / been working", "did / work"], correctAnswerId: "c", explanation: "'How long' with an activity continuing to now uses Present Perfect Continuous.", teachingImplication: "Review duration questions with Present Perfect Continuous.", tags: ["how-long", "work", "present-perfect-continuous"] },
  { id: "q015", itemType: "meaning-contrast", difficultyBand: "hard", targetTense: "present perfect vs present perfect continuous", diagnosticArea: "perfect-aspect-control", prompt: "Which sentence focuses more on the activity itself, not only the result?", options: ["I have written three reports.", "I have been writing reports all afternoon.", "I wrote three reports yesterday.", "I had written the reports before lunch."], correctAnswerId: "b", explanation: "Present Perfect Continuous emphasizes the ongoing activity.", teachingImplication: "Contrast completion/result vs ongoing activity.", tags: ["perfect-aspect", "activity-focus"] },
  { id: "q016", itemType: "dialogue-completion", difficultyBand: "hard", targetTense: "present perfect continuous", diagnosticArea: "perfect-aspect-control", prompt: "A: Your eyes look tired.\nB: Yes, I ___ at the screen for hours.", options: ["look", "looked", "have been looking", "had looked"], correctAnswerId: "c", explanation: "The action continued until recently and explains the present result.", teachingImplication: "Teach recent activity causing present evidence.", tags: ["present-perfect-continuous", "present-evidence"] },
  { id: "q017", itemType: "error-correction", difficultyBand: "hard", targetTense: "present perfect continuous", diagnosticArea: "perfect-aspect-control", prompt: "Choose the best correction: 'She works on this project for three weeks, and she still hasn't finished.'", options: ["She worked on this project for three weeks.", "She has been working on this project for three weeks.", "She had worked on this project for three weeks.", "She is work on this project for three weeks."], correctAnswerId: "b", explanation: "The work began in the past and continues now.", teachingImplication: "Review for/since with continuing actions.", tags: ["present-perfect-continuous", "for"] },
  { id: "q018", itemType: "meaning-contrast", difficultyBand: "advanced", targetTense: "present perfect simple vs continuous", diagnosticArea: "advanced-tense-precision", prompt: "Which sentence is most natural if the speaker wants to emphasize the number of completed tasks?", options: ["I have been answering twenty emails.", "I have answered twenty emails.", "I answer twenty emails.", "I had been answering twenty emails."], correctAnswerId: "b", explanation: "Present Perfect Simple emphasizes completed quantity.", teachingImplication: "Teach completed quantity vs ongoing duration.", tags: ["present-perfect-simple", "completed-result"] },
  { id: "q019", itemType: "contextual-choice", difficultyBand: "easy", targetTense: "past simple", diagnosticArea: "past-tense-control", prompt: "I ___ my phone on the bus yesterday.", options: ["lose", "lost", "was losing", "have lost"], correctAnswerId: "b", explanation: "'Yesterday' shows a completed past event.", teachingImplication: "Review Past Simple for completed past actions.", tags: ["past-simple", "completed-event"] },
  { id: "q020", itemType: "contextual-choice", difficultyBand: "medium", targetTense: "past continuous", diagnosticArea: "past-tense-control", prompt: "At 8 p.m. last night, I ___ dinner with my family.", options: ["had", "have had", "was having", "have been having"], correctAnswerId: "c", explanation: "Past Continuous describes an action in progress at a specific past time.", teachingImplication: "Teach Past Continuous for past actions in progress.", tags: ["past-continuous", "in-progress"] },
  { id: "q021", itemType: "mini-story-cloze", difficultyBand: "medium", targetTense: "past simple vs past continuous", diagnosticArea: "narrative-sequencing", prompt: "While I ___ to the station, I ___ an old friend.", options: ["walked / was seeing", "was walking / saw", "have walked / saw", "walk / see"], correctAnswerId: "b", explanation: "Background action uses Past Continuous; interrupting event uses Past Simple.", teachingImplication: "Teach background action + interruption.", tags: ["past-continuous", "past-simple", "interruption"] },
  { id: "q022", itemType: "dialogue-completion", difficultyBand: "medium", targetTense: "past continuous", diagnosticArea: "past-tense-control", prompt: "A: Why didn't you answer my call?\nB: Sorry, I ___ in a meeting.", options: ["sat", "was sitting", "have sat", "had sat"], correctAnswerId: "b", explanation: "The meeting was in progress when the call happened.", teachingImplication: "Use Past Continuous to explain past circumstances.", tags: ["past-continuous", "explanation"] },
  { id: "q023", itemType: "error-correction", difficultyBand: "hard", targetTense: "past simple vs past continuous", diagnosticArea: "tense-contrast-control", prompt: "Choose the best correction: 'I was hearing a strange noise while I was studying.'", options: ["I heard a strange noise while I was studying.", "I was heard a strange noise while I studied.", "I have heard a strange noise while I study.", "I had hearing a strange noise while I studied."], correctAnswerId: "a", explanation: "'Hear' is often used as an event here, so Past Simple is natural.", teachingImplication: "Review event verbs vs background actions.", tags: ["past-simple", "past-continuous", "event-verbs"] },
  { id: "q024", itemType: "timeline-reasoning", difficultyBand: "hard", targetTense: "past simple vs past continuous", diagnosticArea: "tense-contrast-control", prompt: "Which sentence shows that the rain started before the speaker left home and was still happening?", options: ["It rained when I left home.", "It was raining when I left home.", "It has rained when I left home.", "It had rained when I left home."], correctAnswerId: "b", explanation: "Past Continuous shows the rain was already in progress.", teachingImplication: "Teach background conditions in past stories.", tags: ["past-continuous", "timeline"] },
  { id: "q025", itemType: "contextual-choice", difficultyBand: "hard", targetTense: "past perfect", diagnosticArea: "perfect-aspect-control", prompt: "When I arrived at the office, the meeting ___ already ___.", options: ["has / started", "had / started", "was / starting", "did / start"], correctAnswerId: "b", explanation: "Past Perfect shows an action completed before another past action.", teachingImplication: "Teach earlier past vs later past.", tags: ["past-perfect", "earlier-past"] },
  { id: "q026", itemType: "mini-story-cloze", difficultyBand: "hard", targetTense: "past perfect", diagnosticArea: "narrative-sequencing", prompt: "I couldn't log in because I ___ my password.", options: ["forget", "forgot", "had forgotten", "have forgotten"], correctAnswerId: "c", explanation: "Forgetting happened before the past problem.", teachingImplication: "Use Past Perfect to explain causes of past situations.", tags: ["past-perfect", "cause"] },
  { id: "q027", itemType: "contextual-choice", difficultyBand: "hard", targetTense: "past perfect continuous", diagnosticArea: "perfect-aspect-control", prompt: "By the time the teacher arrived, the students ___ for ten minutes.", options: ["waited", "were waiting", "had been waiting", "have waited"], correctAnswerId: "c", explanation: "The waiting continued up to a point in the past.", teachingImplication: "Teach Past Perfect Continuous for duration before a past point.", tags: ["past-perfect-continuous", "duration-before-past"] },
  { id: "q028", itemType: "meaning-contrast", difficultyBand: "advanced", targetTense: "past perfect vs past simple", diagnosticArea: "advanced-tense-precision", prompt: "Which sentence clearly shows that the report was finished before the manager asked for it?", options: ["I finished the report when the manager asked for it.", "I had finished the report when the manager asked for it.", "I was finishing the report when the manager asked for it.", "I have finished the report when the manager asked for it."], correctAnswerId: "b", explanation: "Past Perfect makes the earlier completion clear.", teachingImplication: "Teach Past Perfect for sequencing past events.", tags: ["past-perfect", "sequencing"] },
  { id: "q029", itemType: "error-identification", difficultyBand: "advanced", targetTense: "past perfect", diagnosticArea: "advanced-tense-precision", prompt: "Which sentence is best?", options: ["After I had checked the details, I sent the email.", "After I have checked the details, I sent the email.", "After I was checking the details, I had sent the email.", "After I checking the details, I sent the email."], correctAnswerId: "a", explanation: "Past Perfect can show the checking was completed before sending.", teachingImplication: "Review after/before clauses and past sequencing.", tags: ["past-perfect", "after-before"] },
  { id: "q030", itemType: "meaning-contrast", difficultyBand: "advanced", targetTense: "past perfect", diagnosticArea: "advanced-tense-precision", prompt: "The floor was wet because someone ___ the window open during the storm.", options: ["left", "had left", "had been leaving", "has left"], correctAnswerId: "b", explanation: "'Had left' shows the earlier action that caused the wet floor.", teachingImplication: "Teach Past Perfect for past cause and result.", tags: ["past-perfect", "past-result"] },
  { id: "q031", itemType: "contextual-choice", difficultyBand: "easy", targetTense: "going to", diagnosticArea: "future-tense-control", prompt: "Look at those dark clouds. It ___ rain.", options: ["will", "is going to", "rains", "has rained"], correctAnswerId: "b", explanation: "'Going to' is used for predictions based on present evidence.", teachingImplication: "Teach going to for evidence-based predictions.", tags: ["going-to", "prediction-evidence"] },
  { id: "q032", itemType: "dialogue-completion", difficultyBand: "medium", targetTense: "will", diagnosticArea: "future-tense-control", prompt: "A: I can't carry all these books.\nB: Don't worry. I ___ help you.", options: ["am going to", "help", "will", "am helping"], correctAnswerId: "c", explanation: "'Will' is natural for a spontaneous offer.", teachingImplication: "Teach will for instant decisions and offers.", tags: ["will", "offer"] },
  { id: "q033", itemType: "contextual-choice", difficultyBand: "medium", targetTense: "present continuous for future", diagnosticArea: "future-tense-control", prompt: "I ___ my IELTS tutor at 6 p.m. tomorrow. We arranged it yesterday.", options: ["meet", "am meeting", "will meet", "have met"], correctAnswerId: "b", explanation: "Present Continuous can describe fixed future arrangements.", teachingImplication: "Teach future arrangements with Present Continuous.", tags: ["present-continuous-future", "arrangement"] },
  { id: "q034", itemType: "meaning-contrast", difficultyBand: "hard", targetTense: "will vs going to", diagnosticArea: "tense-contrast-control", prompt: "Which sentence best describes a plan decided before speaking?", options: ["I'll call him now.", "I'm going to call him after lunch.", "I call him yesterday.", "I've called him now."], correctAnswerId: "b", explanation: "'Going to' often shows a prior plan.", teachingImplication: "Contrast spontaneous will and planned going to.", tags: ["will", "going-to", "future-plan"] },
  { id: "q035", itemType: "professional-context", difficultyBand: "hard", targetTense: "future arrangement", diagnosticArea: "professional-academic-tense-use", prompt: "The team ___ the client on Friday to discuss the final proposal.", options: ["is meeting", "meets yesterday", "has met", "had met"], correctAnswerId: "a", explanation: "The sentence describes a scheduled future meeting.", teachingImplication: "Use Present Continuous for scheduled business arrangements.", tags: ["business-english", "future-arrangement"] },
  { id: "q036", itemType: "error-correction", difficultyBand: "medium", targetTense: "going to", diagnosticArea: "future-tense-control", prompt: "Choose the best correction: 'I will visit my doctor tomorrow. I already booked the appointment.'", options: ["I visit my doctor tomorrow.", "I am going to visit my doctor tomorrow.", "I had visited my doctor tomorrow.", "I have visited my doctor tomorrow."], correctAnswerId: "b", explanation: "'Already booked' suggests a plan, so 'going to' is natural.", teachingImplication: "Teach going to for planned future actions.", tags: ["going-to", "planned-future"] },
  { id: "q037", itemType: "contextual-choice", difficultyBand: "hard", targetTense: "future continuous", diagnosticArea: "future-tense-control", prompt: "This time tomorrow, I ___ my speaking exam.", options: ["take", "will be taking", "have taken", "had taken"], correctAnswerId: "b", explanation: "Future Continuous describes an action in progress at a future time.", teachingImplication: "Teach future actions in progress.", tags: ["future-continuous", "future-time"] },
  { id: "q038", itemType: "contextual-choice", difficultyBand: "hard", targetTense: "future perfect", diagnosticArea: "future-tense-control", prompt: "By next Friday, we ___ the project.", options: ["finish", "will finish", "will have finished", "are finishing"], correctAnswerId: "c", explanation: "Future Perfect shows completion before a future deadline.", teachingImplication: "Teach future completion before a point.", tags: ["future-perfect", "by-deadline"] },
  { id: "q039", itemType: "contextual-choice", difficultyBand: "advanced", targetTense: "future perfect continuous", diagnosticArea: "advanced-tense-precision", prompt: "By June, she ___ English for ten years.", options: ["studies", "will study", "will have been studying", "had studied"], correctAnswerId: "c", explanation: "Future Perfect Continuous shows duration up to a future point.", teachingImplication: "Teach future duration up to a future time.", tags: ["future-perfect-continuous", "duration"] },
  { id: "q040", itemType: "meaning-contrast", difficultyBand: "hard", targetTense: "future perfect vs future continuous", diagnosticArea: "tense-contrast-control", prompt: "Which sentence means the action will be completed before 5 p.m.?", options: ["I will be writing the report at 5 p.m.", "I will have written the report by 5 p.m.", "I will write the report at 5 p.m.", "I am writing the report at 5 p.m."], correctAnswerId: "b", explanation: "Future Perfect shows completion before a future time.", teachingImplication: "Contrast future progress and future completion.", tags: ["future-perfect", "future-continuous"] },
  { id: "q041", itemType: "professional-context", difficultyBand: "advanced", targetTense: "future perfect", diagnosticArea: "professional-academic-tense-use", prompt: "By the time the client arrives, the team ___ the presentation slides.", options: ["will prepare", "will be preparing", "will have prepared", "prepared"], correctAnswerId: "c", explanation: "The slides will be completed before the client arrives.", teachingImplication: "Teach future perfect in professional scheduling.", tags: ["business-english", "future-perfect"] },
  { id: "q042", itemType: "error-correction", difficultyBand: "advanced", targetTense: "future perfect continuous", diagnosticArea: "advanced-tense-precision", prompt: "Choose the best sentence.", options: ["By 2030, I will work here for ten years.", "By 2030, I will have been working here for ten years.", "By 2030, I worked here for ten years.", "By 2030, I am working here for ten years."], correctAnswerId: "b", explanation: "Future Perfect Continuous expresses duration up to a future point.", teachingImplication: "Review future duration with by + future time.", tags: ["future-perfect-continuous", "work-duration"] },
  { id: "q043", itemType: "mini-story-cloze", difficultyBand: "medium", targetTense: "past simple / past continuous", diagnosticArea: "narrative-sequencing", prompt: "I ___ home when I suddenly ___ a loud noise.", options: ["walked / was hearing", "was walking / heard", "have walked / heard", "had walked / hear"], correctAnswerId: "b", explanation: "Past Continuous gives background; Past Simple gives the sudden event.", teachingImplication: "Teach narrative background and event sequence.", tags: ["narrative", "past-continuous", "past-simple"] },
  { id: "q044", itemType: "mini-story-cloze", difficultyBand: "hard", targetTense: "past perfect", diagnosticArea: "narrative-sequencing", prompt: "When I opened my bag, I realized that I ___ my wallet at home.", options: ["left", "had left", "have left", "was leaving"], correctAnswerId: "b", explanation: "Leaving the wallet happened before realizing it.", teachingImplication: "Teach Past Perfect in story sequencing.", tags: ["narrative", "past-perfect"] },
  { id: "q045", itemType: "timeline-reasoning", difficultyBand: "hard", targetTense: "past perfect / past simple", diagnosticArea: "narrative-sequencing", prompt: "Choose the best sequence.", options: ["After I finished dinner, I had watched a film.", "After I had finished dinner, I watched a film.", "After I have finished dinner, I watched a film.", "After I was finishing dinner, I had watched a film."], correctAnswerId: "b", explanation: "Past Perfect shows the first action was completed before the second.", teachingImplication: "Teach sequencing with after/before.", tags: ["narrative", "sequence"] },
  { id: "q046", itemType: "mini-story-cloze", difficultyBand: "advanced", targetTense: "mixed past tenses", diagnosticArea: "narrative-sequencing", prompt: "By the time we got to the airport, the plane ___, so we ___ to book another flight.", options: ["left / have had", "had left / had", "was leaving / have", "has left / had"], correctAnswerId: "b", explanation: "The plane left before arrival; then they had to book another flight.", teachingImplication: "Teach earlier past event + later consequence.", tags: ["narrative", "past-perfect", "past-simple"] },
  { id: "q047", itemType: "meaning-contrast", difficultyBand: "hard", targetTense: "past perfect continuous", diagnosticArea: "narrative-sequencing", prompt: "Which sentence explains why Ali was tired when the meeting started?", options: ["Ali worked after the meeting.", "Ali had been working all morning.", "Ali works every morning.", "Ali will be working all morning."], correctAnswerId: "b", explanation: "Past Perfect Continuous explains a past condition caused by earlier activity.", teachingImplication: "Teach past evidence caused by earlier ongoing action.", tags: ["narrative", "past-perfect-continuous"] },
  { id: "q048", itemType: "best-rewrite", difficultyBand: "advanced", targetTense: "mixed past sequence", diagnosticArea: "narrative-sequencing", prompt: "Choose the best rewrite: 'First, the teacher explained the task. Then the students started writing.'", options: ["The students started writing after the teacher had explained the task.", "The students had started writing after the teacher explained the task.", "The teacher has explained the task after the students wrote.", "The students were starting writing after the teacher had explain the task."], correctAnswerId: "a", explanation: "Past Perfect shows the explanation came first.", teachingImplication: "Review Past Perfect for ordered past events.", tags: ["past-perfect", "rewrite"] },
  { id: "q049", itemType: "professional-context", difficultyBand: "medium", targetTense: "present perfect", diagnosticArea: "professional-academic-tense-use", prompt: "Dear Mr. Lewis, I ___ the attached report for your review.", options: ["send", "sent", "have sent", "was sending"], correctAnswerId: "c", explanation: "Present Perfect is natural in emails when the action has present relevance.", teachingImplication: "Teach Present Perfect in professional email contexts.", tags: ["business-email", "present-perfect"] },
  { id: "q050", itemType: "professional-context", difficultyBand: "medium", targetTense: "present continuous", diagnosticArea: "professional-academic-tense-use", prompt: "We ___ the new marketing strategy in today's meeting.", options: ["discuss", "are discussing", "discussed", "have discussed yesterday"], correctAnswerId: "b", explanation: "'Today's meeting' suggests an arranged/current activity.", teachingImplication: "Teach Present Continuous for scheduled/current workplace actions.", tags: ["business-english", "present-continuous"] },
  { id: "q051", itemType: "professional-context", difficultyBand: "hard", targetTense: "future perfect", diagnosticArea: "professional-academic-tense-use", prompt: "By the end of the quarter, our team ___ the training program.", options: ["completes", "will complete", "will have completed", "completed"], correctAnswerId: "c", explanation: "Future Perfect shows completion before a future deadline.", teachingImplication: "Teach deadline-based future reporting.", tags: ["business-english", "future-perfect"] },
  { id: "q052", itemType: "professional-context", difficultyBand: "hard", targetTense: "present perfect continuous", diagnosticArea: "professional-academic-tense-use", prompt: "We ___ customer feedback all week, and we'll present the results tomorrow.", options: ["collect", "collected", "have been collecting", "had collected"], correctAnswerId: "c", explanation: "The activity continued over a recent period and is relevant now.", teachingImplication: "Review ongoing recent work with Present Perfect Continuous.", tags: ["business-english", "present-perfect-continuous"] },
  { id: "q053", itemType: "error-correction", difficultyBand: "hard", targetTense: "past simple vs present perfect", diagnosticArea: "professional-academic-tense-use", prompt: "Choose the best correction: 'We have launched the campaign last Monday.'", options: ["We launched the campaign last Monday.", "We have launched the campaign last Monday.", "We had launched the campaign last Monday.", "We are launching the campaign last Monday."], correctAnswerId: "a", explanation: "'Last Monday' is finished time, so Past Simple is needed.", teachingImplication: "Review finished time in business reporting.", tags: ["business-english", "past-simple"] },
  { id: "q054", itemType: "professional-context", difficultyBand: "advanced", targetTense: "future continuous", diagnosticArea: "professional-academic-tense-use", prompt: "At this time next week, the sales team ___ with clients in Dubai.", options: ["will meet", "will be meeting", "will have met", "meets"], correctAnswerId: "b", explanation: "Future Continuous describes an action in progress at a future time.", teachingImplication: "Teach Future Continuous in scheduling and planning.", tags: ["business-english", "future-continuous"] },
  { id: "q055", itemType: "ielts-speaking-response", difficultyBand: "medium", targetTense: "present perfect", diagnosticArea: "perfect-aspect-control", prompt: "I ___ several cities in my country, but I still want to visit more.", options: ["visit", "visited yesterday", "have visited", "was visiting"], correctAnswerId: "c", explanation: "The speaker is talking about life experience.", teachingImplication: "Teach Present Perfect for IELTS Speaking Part 1 experience answers.", tags: ["ielts-speaking", "present-perfect"] },
  { id: "q056", itemType: "ielts-speaking-response", difficultyBand: "medium", targetTense: "past simple", diagnosticArea: "past-tense-control", prompt: "Last summer, I ___ to Alexandria with my family.", options: ["go", "went", "have gone", "was going every summer"], correctAnswerId: "b", explanation: "'Last summer' is a finished past time.", teachingImplication: "Teach Past Simple for IELTS personal stories.", tags: ["ielts-speaking", "past-simple"] },
  { id: "q057", itemType: "ielts-speaking-response", difficultyBand: "hard", targetTense: "past habit / past simple", diagnosticArea: "past-tense-control", prompt: "When I was younger, I ___ much more time outdoors than I do now.", options: ["spend", "have spent", "spent", "was spent"], correctAnswerId: "c", explanation: "Past Simple can describe a past habit or repeated past situation in context.", teachingImplication: "Teach past habits and comparison with the present.", tags: ["ielts-speaking", "past-habit"] },
  { id: "q058", itemType: "ielts-speaking-response", difficultyBand: "hard", targetTense: "mixed past tenses", diagnosticArea: "narrative-sequencing", prompt: "I ___ for the bus when I realized that I ___ my notes at home.", options: ["waited / left", "was waiting / had left", "have waited / was leaving", "had waited / have left"], correctAnswerId: "b", explanation: "The waiting was in progress; leaving the notes happened earlier.", teachingImplication: "Teach storytelling tense control for IELTS Speaking Part 2.", tags: ["ielts-speaking", "narrative", "past-perfect"] },
  { id: "q059", itemType: "ielts-speaking-response", difficultyBand: "hard", targetTense: "present simple", diagnosticArea: "present-tense-control", prompt: "In general, people ___ better when they have a clear goal.", options: ["learn", "are learning", "learned", "have learned yesterday"], correctAnswerId: "a", explanation: "Present Simple expresses general truths and opinions.", teachingImplication: "Teach Present Simple for general IELTS opinions.", tags: ["ielts-speaking", "present-simple", "generalization"] },
  { id: "q060", itemType: "ielts-speaking-response", difficultyBand: "advanced", targetTense: "future perfect", diagnosticArea: "advanced-tense-precision", prompt: "By the time I finish university, I hope I ___ enough experience to start my career.", options: ["gain", "will have gained", "gained", "was gaining"], correctAnswerId: "b", explanation: "Future Perfect shows completion before a future point.", teachingImplication: "Teach advanced future forms for future plans and ambitions.", tags: ["ielts-speaking", "future-perfect"] },
  { id: "q061", itemType: "error-correction", difficultyBand: "medium", targetTense: "present simple", diagnosticArea: "present-tense-control", prompt: "Choose the best correction: 'She go to work by bus every day.'", options: ["She goes to work by bus every day.", "She is go to work by bus every day.", "She went to work by bus every day now.", "She has go to work by bus every day."], correctAnswerId: "a", explanation: "Third-person singular in Present Simple needs -s.", teachingImplication: "Review third-person -s.", tags: ["present-simple", "third-person-s"] },
  { id: "q062", itemType: "error-correction", difficultyBand: "medium", targetTense: "present continuous", diagnosticArea: "present-tense-control", prompt: "Choose the best correction: 'They are study English now.'", options: ["They study English now.", "They are studying English now.", "They studied English now.", "They have study English now."], correctAnswerId: "b", explanation: "Present Continuous uses be + verb-ing.", teachingImplication: "Review form of Present Continuous.", tags: ["present-continuous", "form"] },
  { id: "q063", itemType: "error-correction", difficultyBand: "hard", targetTense: "present perfect", diagnosticArea: "perfect-aspect-control", prompt: "Choose the best correction: 'I live here since 2020.'", options: ["I lived here since 2020.", "I have lived here since 2020.", "I am living here since 2020 yesterday.", "I had live here since 2020."], correctAnswerId: "b", explanation: "'Since 2020' connects past to present.", teachingImplication: "Review Present Perfect with since.", tags: ["present-perfect", "since"] },
  { id: "q064", itemType: "error-correction", difficultyBand: "hard", targetTense: "past perfect", diagnosticArea: "perfect-aspect-control", prompt: "Choose the best correction: 'When I arrived, they already left.'", options: ["When I arrived, they had already left.", "When I arrived, they have already left.", "When I arrived, they were already leave.", "When I arrived, they already leaving."], correctAnswerId: "a", explanation: "Leaving happened before arriving, so Past Perfect is needed.", teachingImplication: "Teach earlier past event with Past Perfect.", tags: ["past-perfect", "correction"] },
  { id: "q065", itemType: "error-correction", difficultyBand: "advanced", targetTense: "future perfect", diagnosticArea: "advanced-tense-precision", prompt: "Choose the best correction: 'By next year, I will finish my master's degree for two years.'", options: ["By next year, I finished my master's degree.", "By next year, I will have finished my master's degree.", "By next year, I am finishing my master's degree yesterday.", "By next year, I have finished my master's degree last year."], correctAnswerId: "b", explanation: "Future Perfect shows completion before a future point.", teachingImplication: "Teach future deadlines and completion.", tags: ["future-perfect", "correction"] },
  { id: "q066", itemType: "error-correction", difficultyBand: "advanced", targetTense: "tense sequence", diagnosticArea: "advanced-tense-precision", prompt: "Choose the best correction: 'I had been working when I have received your message.'", options: ["I was working when I received your message.", "I have been working when I received your message.", "I had work when I receive your message.", "I am working when I had received your message."], correctAnswerId: "a", explanation: "Past Continuous + Past Simple is natural for background action and interrupting event.", teachingImplication: "Review tense sequencing in past events.", tags: ["past-continuous", "past-simple", "correction"] },
  { id: "q067", itemType: "best-rewrite", difficultyBand: "medium", targetTense: "present perfect continuous", diagnosticArea: "perfect-aspect-control", prompt: "Choose the best rewrite: 'I started this course two months ago, and I am still taking it.'", options: ["I took this course two months ago.", "I have been taking this course for two months.", "I had taken this course for two months yesterday.", "I take this course two months ago."], correctAnswerId: "b", explanation: "Present Perfect Continuous shows continuing duration.", teachingImplication: "Teach for + duration with ongoing actions.", tags: ["present-perfect-continuous", "rewrite"] },
  { id: "q068", itemType: "best-rewrite", difficultyBand: "hard", targetTense: "past perfect", diagnosticArea: "perfect-aspect-control", prompt: "Choose the best rewrite: 'First, Omar lost his phone. Then he called the police.'", options: ["Omar had lost his phone before he called the police.", "Omar has lost his phone before he called the police.", "Omar was losing his phone before he calls the police.", "Omar loses his phone before he had called the police."], correctAnswerId: "a", explanation: "Past Perfect shows the earlier event.", teachingImplication: "Teach past event ordering.", tags: ["past-perfect", "rewrite"] },
  { id: "q069", itemType: "best-rewrite", difficultyBand: "hard", targetTense: "future arrangement", diagnosticArea: "future-tense-control", prompt: "Choose the sentence that means the meeting is already arranged.", options: ["We will meet the client one day.", "We are meeting the client at 3 p.m. tomorrow.", "We meet the client yesterday.", "We have met the client last week."], correctAnswerId: "b", explanation: "Present Continuous can show fixed future arrangements.", teachingImplication: "Teach scheduled future arrangements.", tags: ["present-continuous-future", "rewrite"] },
  { id: "q070", itemType: "best-rewrite", difficultyBand: "advanced", targetTense: "future perfect continuous", diagnosticArea: "advanced-tense-precision", prompt: "Choose the best rewrite: 'In 2030, it will be ten years since I started teaching online.'", options: ["In 2030, I will teach online for ten years.", "In 2030, I will have been teaching online for ten years.", "In 2030, I taught online for ten years.", "In 2030, I have been teaching online yesterday."], correctAnswerId: "b", explanation: "Future Perfect Continuous shows duration up to a future point.", teachingImplication: "Teach future duration with will have been + -ing.", tags: ["future-perfect-continuous", "rewrite"] },
  { id: "q071", itemType: "best-rewrite", difficultyBand: "advanced", targetTense: "present perfect result", diagnosticArea: "advanced-tense-precision", prompt: "Choose the closest meaning: 'The manager has cancelled the meeting.'", options: ["The meeting is cancelled now.", "The manager cancels meetings every week.", "The manager cancelled the meeting in 2019 only.", "The meeting was happening when he cancelled it."], correctAnswerId: "a", explanation: "Present Perfect often shows a present result.", teachingImplication: "Teach present results of past actions.", tags: ["present-perfect", "result"] },
  { id: "q072", itemType: "best-rewrite", difficultyBand: "advanced", targetTense: "past perfect contrast", diagnosticArea: "advanced-tense-precision", prompt: "Choose the sentence that makes the timeline clearest.", options: ["I sent the email after I checked the report.", "I sent the email after I had checked the report.", "I have sent the email after I checked the report yesterday.", "I was sending the email after I check the report."], correctAnswerId: "b", explanation: "Past Perfect makes the earlier action clear.", teachingImplication: "Teach clarity in past sequencing.", tags: ["past-perfect", "clarity"] },
  { id: "q073", itemType: "timeline-reasoning", difficultyBand: "medium", targetTense: "present perfect", diagnosticArea: "perfect-aspect-control", prompt: "Which sentence connects the past with the present?", options: ["I lost my keys yesterday.", "I have lost my keys.", "I was losing my keys when you called.", "I had lost my keys before I arrived."], correctAnswerId: "b", explanation: "Present Perfect links a past event to the present situation.", teachingImplication: "Review past-to-present connection.", tags: ["present-perfect", "timeline"] },
  { id: "q074", itemType: "timeline-reasoning", difficultyBand: "medium", targetTense: "past continuous", diagnosticArea: "past-tense-control", prompt: "Which sentence means the action was in progress at 9 p.m.?", options: ["I studied at 9 p.m.", "I was studying at 9 p.m.", "I have studied at 9 p.m.", "I had studied at 9 p.m."], correctAnswerId: "b", explanation: "Past Continuous shows an action in progress at a past time.", teachingImplication: "Teach past-in-progress meaning.", tags: ["past-continuous", "timeline"] },
  { id: "q075", itemType: "timeline-reasoning", difficultyBand: "hard", targetTense: "past perfect", diagnosticArea: "perfect-aspect-control", prompt: "Which sentence means the train left before I arrived?", options: ["The train left when I arrived.", "The train was leaving when I arrived.", "The train had left when I arrived.", "The train has left when I arrived."], correctAnswerId: "c", explanation: "Past Perfect shows the train left earlier.", teachingImplication: "Teach earlier/later past events.", tags: ["past-perfect", "timeline"] },
  { id: "q076", itemType: "timeline-reasoning", difficultyBand: "hard", targetTense: "future continuous", diagnosticArea: "future-tense-control", prompt: "Which sentence means the speaker will be in the middle of the action at 10 a.m. tomorrow?", options: ["I will start the exam at 10 a.m.", "I will be taking the exam at 10 a.m.", "I will have taken the exam by 10 a.m.", "I took the exam at 10 a.m."], correctAnswerId: "b", explanation: "Future Continuous shows an action in progress at a future time.", teachingImplication: "Contrast future start, progress, and completion.", tags: ["future-continuous", "timeline"] },
  { id: "q077", itemType: "timeline-reasoning", difficultyBand: "advanced", targetTense: "future perfect", diagnosticArea: "advanced-tense-precision", prompt: "Which sentence means the work will be finished before Monday?", options: ["We will work on the project on Monday.", "We will be working on the project on Monday.", "We will have finished the project by Monday.", "We finished the project on Monday."], correctAnswerId: "c", explanation: "Future Perfect shows completion before a future time.", teachingImplication: "Teach by + future time.", tags: ["future-perfect", "timeline"] },
  { id: "q078", itemType: "timeline-reasoning", difficultyBand: "advanced", targetTense: "perfect continuous", diagnosticArea: "advanced-tense-precision", prompt: "Which sentence focuses on duration continuing up to now?", options: ["She worked here for five years, but she left.", "She has been working here for five years.", "She was working here at 5 p.m.", "She had worked here before 2010."], correctAnswerId: "b", explanation: "Present Perfect Continuous shows duration up to now.", teachingImplication: "Teach continuing duration.", tags: ["present-perfect-continuous", "duration"] },
  { id: "q079", itemType: "dialogue-completion", difficultyBand: "easy", targetTense: "present simple", diagnosticArea: "present-tense-control", prompt: "A: What time does the class start?\nB: It ___ at seven.", options: ["start", "starts", "is starting yesterday", "has started every day"], correctAnswerId: "b", explanation: "Timetables and routines often use Present Simple.", teachingImplication: "Teach Present Simple for schedules.", tags: ["present-simple", "schedule"] },
  { id: "q080", itemType: "dialogue-completion", difficultyBand: "medium", targetTense: "present continuous", diagnosticArea: "present-tense-control", prompt: "A: Can I call you now?\nB: Not now. I ___ my homework.", options: ["do", "did", "am doing", "have done yesterday"], correctAnswerId: "c", explanation: "The action is happening now.", teachingImplication: "Review now-actions with Present Continuous.", tags: ["present-continuous", "now"] },
  { id: "q081", itemType: "dialogue-completion", difficultyBand: "medium", targetTense: "present perfect", diagnosticArea: "perfect-aspect-control", prompt: "A: Have you sent the application?\nB: Yes, I ___ it this morning.", options: ["sent", "have sent", "was sending", "had sent tomorrow"], correctAnswerId: "b", explanation: "In response to a present perfect question, Present Perfect is natural when the result matters now.", teachingImplication: "Teach conversational present relevance.", tags: ["present-perfect", "dialogue"] },
  { id: "q082", itemType: "dialogue-completion", difficultyBand: "hard", targetTense: "past perfect", diagnosticArea: "perfect-aspect-control", prompt: "A: Why was Sara upset?\nB: Because she ___ the deadline.", options: ["missed", "had missed", "has missed tomorrow", "was missing every day"], correctAnswerId: "b", explanation: "Missing the deadline happened before the past feeling.", teachingImplication: "Teach past cause before past emotional result.", tags: ["past-perfect", "dialogue"] },
  { id: "q083", itemType: "dialogue-completion", difficultyBand: "hard", targetTense: "future arrangement", diagnosticArea: "future-tense-control", prompt: "A: Are you free tomorrow afternoon?\nB: Sorry, I ___ my professor at 4.", options: ["meet", "met", "am meeting", "have met"], correctAnswerId: "c", explanation: "The meeting is arranged, so Present Continuous is natural.", teachingImplication: "Review future arrangements.", tags: ["present-continuous-future", "dialogue"] },
  { id: "q084", itemType: "dialogue-completion", difficultyBand: "advanced", targetTense: "future perfect", diagnosticArea: "advanced-tense-precision", prompt: "A: Will the report be ready before the meeting?\nB: Yes, we ___ it by then.", options: ["finish", "will have finished", "were finishing", "have finished yesterday"], correctAnswerId: "b", explanation: "'By then' requires future completion.", teachingImplication: "Teach Future Perfect with by then/by the time.", tags: ["future-perfect", "dialogue"] },
  { id: "q085", itemType: "stative-verb", difficultyBand: "medium", targetTense: "present simple", diagnosticArea: "stative-dynamic-control", prompt: "I ___ this answer is correct.", options: ["am thinking", "think", "have thought", "was thinking"], correctAnswerId: "b", explanation: "'Think' meaning 'believe' is stative and normally uses Present Simple.", teachingImplication: "Teach stative meanings of common verbs.", tags: ["stative-verbs", "think"] },
  { id: "q086", itemType: "dynamic-meaning", difficultyBand: "hard", targetTense: "present continuous", diagnosticArea: "stative-dynamic-control", prompt: "I ___ about changing my job, but I haven't decided yet.", options: ["think", "am thinking", "thought yesterday", "had thought tomorrow"], correctAnswerId: "b", explanation: "'Think about' can be dynamic when it means considering.", teachingImplication: "Teach stative vs dynamic meanings.", tags: ["stative-dynamic", "think-about"] },
  { id: "q087", itemType: "stative-verb", difficultyBand: "medium", targetTense: "present simple", diagnosticArea: "stative-dynamic-control", prompt: "This soup ___ delicious.", options: ["tastes", "is tasting", "has tasted yesterday", "had been tasting"], correctAnswerId: "a", explanation: "'Taste' here describes a state or quality.", teachingImplication: "Teach sensory verbs as stative when describing qualities.", tags: ["stative-verbs", "sensory-verbs"] },
  { id: "q088", itemType: "dynamic-meaning", difficultyBand: "hard", targetTense: "present continuous", diagnosticArea: "stative-dynamic-control", prompt: "The chef ___ the soup to check if it needs more salt.", options: ["tastes", "is tasting", "tasted always", "has been tasted"], correctAnswerId: "b", explanation: "Here 'taste' is an action, so Present Continuous is possible.", teachingImplication: "Teach dynamic uses of sensory verbs.", tags: ["dynamic-verbs", "sensory-verbs"] },
  { id: "q089", itemType: "stative-verb", difficultyBand: "hard", targetTense: "present simple", diagnosticArea: "stative-dynamic-control", prompt: "I ___ a new laptop, but I don't use it much.", options: ["am having", "have", "had been having", "am had"], correctAnswerId: "b", explanation: "'Have' meaning possession is stative.", teachingImplication: "Review stative possession with have.", tags: ["have", "stative"] },
  { id: "q090", itemType: "dynamic-meaning", difficultyBand: "hard", targetTense: "present continuous", diagnosticArea: "stative-dynamic-control", prompt: "We ___ lunch with a client right now.", options: ["have", "are having", "had had", "have had yesterday"], correctAnswerId: "b", explanation: "'Have lunch' is an action, so Present Continuous is natural.", teachingImplication: "Teach dynamic expressions with have.", tags: ["have", "dynamic", "business"] },
  { id: "q091", itemType: "advanced-context", difficultyBand: "advanced", targetTense: "tense consistency", diagnosticArea: "professional-academic-tense-use", prompt: "The findings suggest that remote workers ___ more productive when they ___ clear communication rules.", options: ["are / have", "were / will have", "had been / have had", "have been / had"], correctAnswerId: "a", explanation: "General findings are often expressed with Present Simple.", teachingImplication: "Teach tense consistency in reports and general claims.", tags: ["present-simple", "academic-style"] },
  { id: "q092", itemType: "advanced-context", difficultyBand: "advanced", targetTense: "past perfect / passive", diagnosticArea: "professional-academic-tense-use", prompt: "The proposal was rejected because several key risks ___ during the planning stage.", options: ["overlooked", "had been overlooked", "have overlooked", "were overlooking"], correctAnswerId: "b", explanation: "The risks were overlooked before the proposal was rejected.", teachingImplication: "Teach Past Perfect Passive for earlier causes.", tags: ["past-perfect-passive", "professional"] },
  { id: "q093", itemType: "advanced-context", difficultyBand: "advanced", targetTense: "future perfect continuous", diagnosticArea: "advanced-tense-precision", prompt: "By the time the new system is launched, the team ___ on it for almost two years.", options: ["works", "will work", "will have been working", "had worked"], correctAnswerId: "c", explanation: "Future Perfect Continuous shows duration up to a future point.", teachingImplication: "Teach advanced future duration.", tags: ["future-perfect-continuous", "professional"] },
  { id: "q094", itemType: "advanced-context", difficultyBand: "advanced", targetTense: "present perfect continuous / trend", diagnosticArea: "professional-academic-tense-use", prompt: "Researchers ___ the effects of screen time for years, but the debate is still open.", options: ["study", "studied", "have been studying", "had studied tomorrow"], correctAnswerId: "c", explanation: "The research activity started in the past and continues now.", teachingImplication: "Teach ongoing research/trend descriptions.", tags: ["present-perfect-continuous", "academic"] },
  { id: "q095", itemType: "advanced-context", difficultyBand: "advanced", targetTense: "tense and register", diagnosticArea: "professional-academic-tense-use", prompt: "Which sentence is most suitable in a formal report?", options: ["We found that customer satisfaction has increased steadily since January.", "We find yesterday that customer satisfaction increases since January.", "We have found yesterday that customer satisfaction increased since January.", "We were finding that customer satisfaction has increase since January."], correctAnswerId: "a", explanation: "This sentence uses accurate tense and formal reporting style.", teachingImplication: "Teach report-writing tense control.", tags: ["formal-register", "present-perfect", "report"] },
  { id: "q096", itemType: "advanced-context", difficultyBand: "advanced", targetTense: "complex tense contrast", diagnosticArea: "advanced-tense-precision", prompt: "Choose the most natural sentence.", options: ["I have been working on the issue when you called me yesterday.", "I was working on the issue when you called me yesterday.", "I had worked on the issue when you call me yesterday.", "I am working on the issue when you called me yesterday."], correctAnswerId: "b", explanation: "Past Continuous + Past Simple is natural for a past interrupted action.", teachingImplication: "Review tense consistency with past time markers.", tags: ["past-continuous", "past-simple", "advanced-review"] },
];

function relatedTrackTags(tags: string[]): PlacementItem["relatedTrackTags"] {
  const trackSet = new Set<PlacementItem["relatedTrackTags"][number]>(["general"]);

  if (tags.some((tag) => tag.includes("ielts"))) trackSet.add("ielts");
  if (
    tags.some(
      (tag) =>
        tag.includes("business") ||
        tag.includes("workplace") ||
        tag.includes("professional"),
    )
  ) {
    trackSet.add("business");
  }
  if (
    tags.some(
      (tag) =>
        tag.includes("advanced") ||
        tag.includes("academic") ||
        tag.includes("formal-register"),
    )
  ) {
    trackSet.add("teacher-training");
  }

  return Array.from(trackSet);
}

export const tenseItems: PlacementItem[] = seeds.map((item, index) => ({
  id: item.id,
  itemType: item.itemType,
  difficulty: difficultyValue[item.difficultyBand],
  difficultyBand: item.difficultyBand,
  targetTense: item.targetTense,
  diagnosticArea: item.diagnosticArea,
  stem: item.prompt,
  context: item.itemType.replaceAll("-", " "),
  options: item.options.map((text, optionIndex) => ({
    id: optionIds[optionIndex],
    text,
  })),
  correctAnswerId: item.correctAnswerId,
  explanation: item.explanation,
  feedbackIfWrong:
    "The incorrect options show a common tense error, time-marker error, or meaning mismatch.",
  teachingImplication: item.teachingImplication,
  recommendationTags: item.tags,
  relatedTrackTags: relatedTrackTags(item.tags),
  estimatedTimeSeconds:
    item.difficultyBand === "advanced" ? 36 : item.difficultyBand === "hard" ? 32 : 26,
  isAnchorItem: index % 12 === 0,
  isRoutingItem: routingIds.has(item.id),
  isConfirmationItem:
    item.difficultyBand === "hard" ||
    item.itemType === "timeline-reasoning" ||
    item.itemType === "meaning-contrast" ||
    index % 5 === 0,
  avoidIfSeenRecently: true,
  version: 1,
}));

export const requiredTenseDistribution = {
  total: 96,
  difficulty: {
    easy: seeds.filter((item) => item.difficultyBand === "easy").length,
    medium: seeds.filter((item) => item.difficultyBand === "medium").length,
    hard: seeds.filter((item) => item.difficultyBand === "hard").length,
    advanced: seeds.filter((item) => item.difficultyBand === "advanced").length,
  },
};
