export type SoundGroup = "consonants" | "vowels";

export type SoundWord = {
  text: string;
  ipa: string;
};

export type MinimalPair = {
  left: string;
  leftIpa: string;
  right: string;
  rightIpa: string;
};

export type SoundLesson = {
  id: string;
  group: SoundGroup;
  ipa: string;
  title: string;
  example: SoundWord;
  audioText: string;
  soundType: string;
  hint: string;
  mouthPosition: string;
  spellings: string[];
  words: SoundWord[];
  minimalPairs: MinimalPair[];
  sentences: string[];
  commonMistake: string;
  correctionTip: string;
  practiceDrill: string;
  homework: string;
};

export type CourseModule = {
  id: string;
  number: string;
  title: string;
  eyebrow: string;
  description: string;
  learn: string[];
  examples: Array<{
    label: string;
    text: string;
    note?: string;
  }>;
  practice: string[];
  quiz: Array<{
    question: string;
    answer: string;
  }>;
};

export const coursePath = "/american-english-phonetics-course";

export const phoneticsNavItems = [
  { id: "course-overview", label: "Course Overview" },
  { id: "ipa-sound-chart", label: "IPA and Sound Chart" },
  { id: "consonant-sounds", label: "Consonant Sounds" },
  { id: "vowel-sounds", label: "Vowel Sounds" },
  { id: "syllables", label: "Syllables" },
  { id: "word-stress", label: "Word Stress" },
  { id: "sentence-stress", label: "Sentence Stress" },
  { id: "rhythm", label: "Rhythm" },
  { id: "intonation", label: "Intonation" },
  { id: "connected-speech", label: "Connected Speech" },
  { id: "silent-letters", label: "Silent Letters" },
  { id: "spelling-to-sound-patterns", label: "Spelling-to-Sound Patterns" },
  { id: "final-sounds", label: "Final Sounds" },
  { id: "s-endings", label: "-s Endings" },
  { id: "ed-endings", label: "-ed Endings" },
  { id: "common-mistakes", label: "Common Mistakes" },
  { id: "practice-activities", label: "Practice Activities" },
  { id: "review-tests", label: "Review Tests" },
  { id: "final-project", label: "Final Project" },
] as const;

export const courseBenefits = [
  "Master American English consonant sounds.",
  "Learn American English vowel sounds clearly.",
  "Understand IPA symbols without confusion.",
  "Improve syllables, word stress, and sentence rhythm.",
  "Practice intonation and connected speech.",
  "Pronounce final sounds, -s endings, and -ed endings correctly.",
  "Avoid common ESL pronunciation mistakes.",
  "Study freely without creating an account.",
] as const;

export const studyPath = [
  "Start with the IPA and sound chart.",
  "Study one sound lesson at a time.",
  "Listen to the native-style audio support.",
  "Repeat the sound, words, and sentences.",
  "Practice the minimal pairs.",
  "Record yourself and compare.",
  "Complete the review tests.",
] as const;

export const practiceChecklistItems = [
  "I listened to the sound.",
  "I repeated the words.",
  "I practiced the minimal pairs.",
  "I read the sentences.",
  "I recorded myself.",
] as const;

export const consonantLessons: SoundLesson[] = [
  {
    id: "p",
    group: "consonants",
    ipa: "/p/",
    title: "/p/ as in pen",
    example: { text: "pen", ipa: "/pɛn/" },
    audioText: "p. pen. Please put the pen on the paper.",
    soundType: "Voiceless stop consonant",
    hint: "Close both lips, build air, then release with a small puff.",
    mouthPosition: "Put both lips together. Stop the air. Open the lips quickly. Keep the voice off.",
    spellings: ["p: pen", "pp: happy"],
    words: [
      { text: "pen", ipa: "/pɛn/" },
      { text: "paper", ipa: "/ˈpeɪpɚ/" },
      { text: "happy", ipa: "/ˈhæpi/" },
      { text: "cup", ipa: "/kʌp/" },
    ],
    minimalPairs: [
      { left: "pat", leftIpa: "/pæt/", right: "bat", rightIpa: "/bæt/" },
      { left: "pin", leftIpa: "/pɪn/", right: "bin", rightIpa: "/bɪn/" },
      { left: "cap", leftIpa: "/kæp/", right: "cab", rightIpa: "/kæb/" },
    ],
    sentences: ["Please put the pen on the paper."],
    commonMistake: "Some learners pronounce /p/ like /b/ because they add voice.",
    correctionTip: "Hold your throat gently. You should feel air, not vibration.",
    practiceDrill: "Repeat: pa, pa, pa. Then: pat, pen, paper, cup.",
    homework: "Record ten /p/ words at the beginning and end of words.",
  },
  {
    id: "b",
    group: "consonants",
    ipa: "/b/",
    title: "/b/ as in book",
    example: { text: "book", ipa: "/bʊk/" },
    audioText: "b. book. Bring the blue book back.",
    soundType: "Voiced stop consonant",
    hint: "Close both lips and release with voice.",
    mouthPosition: "Put both lips together. Stop the air. Release while your vocal cords vibrate.",
    spellings: ["b: book", "bb: rubber"],
    words: [
      { text: "book", ipa: "/bʊk/" },
      { text: "baby", ipa: "/ˈbeɪbi/" },
      { text: "table", ipa: "/ˈteɪbəl/" },
      { text: "cab", ipa: "/kæb/" },
    ],
    minimalPairs: [
      { left: "bat", leftIpa: "/bæt/", right: "pat", rightIpa: "/pæt/" },
      { left: "bin", leftIpa: "/bɪn/", right: "pin", rightIpa: "/pɪn/" },
      { left: "cab", leftIpa: "/kæb/", right: "cap", rightIpa: "/kæp/" },
    ],
    sentences: ["Bring the blue book back."],
    commonMistake: "Final /b/ may become /p/ if the voice disappears.",
    correctionTip: "Keep a gentle vibration through the final consonant.",
    practiceDrill: "Repeat: ba, ba, ba. Then contrast: cap, cab; rope, robe.",
    homework: "Read five short sentences with final /b/ and keep the ending voiced.",
  },
  {
    id: "t",
    group: "consonants",
    ipa: "/t/",
    title: "/t/ as in time",
    example: { text: "time", ipa: "/taɪm/" },
    audioText: "t. time. Take the test on Tuesday.",
    soundType: "Voiceless stop consonant",
    hint: "Touch the ridge behind your top teeth and release air.",
    mouthPosition: "Place the tongue tip on the alveolar ridge. Stop the air. Release without voice.",
    spellings: ["t: time", "tt: letter", "ed: walked"],
    words: [
      { text: "time", ipa: "/taɪm/" },
      { text: "today", ipa: "/təˈdeɪ/" },
      { text: "water", ipa: "/ˈwɑtɚ/" },
      { text: "cat", ipa: "/kæt/" },
    ],
    minimalPairs: [
      { left: "ten", leftIpa: "/tɛn/", right: "den", rightIpa: "/dɛn/" },
      { left: "tie", leftIpa: "/taɪ/", right: "die", rightIpa: "/daɪ/" },
      { left: "seat", leftIpa: "/sit/", right: "seed", rightIpa: "/sid/" },
    ],
    sentences: ["Take the test on Tuesday."],
    commonMistake: "Learners may make /t/ too dental or add a vowel after final /t/.",
    correctionTip: "Touch the ridge behind the teeth and finish cleanly: cat, not cat-uh.",
    practiceDrill: "Repeat: tea, tie, ten, cat, seat.",
    homework: "Mark final /t/ in a paragraph and read it without adding extra vowels.",
  },
  {
    id: "d",
    group: "consonants",
    ipa: "/d/",
    title: "/d/ as in day",
    example: { text: "day", ipa: "/deɪ/" },
    audioText: "d. day. Dan did the dishes today.",
    soundType: "Voiced stop consonant",
    hint: "Use the same tongue place as /t/, but add voice.",
    mouthPosition: "Touch the alveolar ridge with the tongue tip. Stop the air. Release with vibration.",
    spellings: ["d: day", "dd: ladder", "ed: played"],
    words: [
      { text: "day", ipa: "/deɪ/" },
      { text: "dinner", ipa: "/ˈdɪnɚ/" },
      { text: "ladder", ipa: "/ˈlædɚ/" },
      { text: "red", ipa: "/rɛd/" },
    ],
    minimalPairs: [
      { left: "do", leftIpa: "/du/", right: "two", rightIpa: "/tu/" },
      { left: "den", leftIpa: "/dɛn/", right: "ten", rightIpa: "/tɛn/" },
      { left: "seed", leftIpa: "/sid/", right: "seat", rightIpa: "/sit/" },
    ],
    sentences: ["Dan did the dishes today."],
    commonMistake: "Final /d/ can become /t/ if the voice stops too early.",
    correctionTip: "Lengthen the vowel slightly before final /d/: bad, bed, made.",
    practiceDrill: "Repeat: do, day, done, red, made.",
    homework: "Practice ten past-tense verbs that end in /d/: played, lived, called.",
  },
  {
    id: "k",
    group: "consonants",
    ipa: "/k/",
    title: "/k/ as in cat",
    example: { text: "cat", ipa: "/kæt/" },
    audioText: "k. cat. Keep the cup in the kitchen.",
    soundType: "Voiceless stop consonant",
    hint: "Lift the back of your tongue, stop the air, then release.",
    mouthPosition: "Raise the back of the tongue to the soft palate. Release without voice.",
    spellings: ["c: cat", "k: keep", "ck: back", "ch: school"],
    words: [
      { text: "cat", ipa: "/kæt/" },
      { text: "keep", ipa: "/kip/" },
      { text: "school", ipa: "/skul/" },
      { text: "back", ipa: "/bæk/" },
    ],
    minimalPairs: [
      { left: "came", leftIpa: "/keɪm/", right: "game", rightIpa: "/geɪm/" },
      { left: "coat", leftIpa: "/koʊt/", right: "goat", rightIpa: "/goʊt/" },
      { left: "back", leftIpa: "/bæk/", right: "bag", rightIpa: "/bæg/" },
    ],
    sentences: ["Keep the cup in the kitchen."],
    commonMistake: "Some learners make /k/ too weak at the ends of words.",
    correctionTip: "Release the final /k/ lightly, especially before a vowel.",
    practiceDrill: "Repeat: key, car, cup, back, take.",
    homework: "Read a list of words with c, k, ck, and ch pronounced /k/.",
  },
  {
    id: "g",
    group: "consonants",
    ipa: "/g/",
    title: "/g/ as in go",
    example: { text: "go", ipa: "/goʊ/" },
    audioText: "g. go. Gary got a good grade.",
    soundType: "Voiced stop consonant",
    hint: "Use the back of your tongue and keep the voice on.",
    mouthPosition: "Raise the back of the tongue to the soft palate. Release with vibration.",
    spellings: ["g: go", "gg: bigger", "gh: ghost"],
    words: [
      { text: "go", ipa: "/goʊ/" },
      { text: "good", ipa: "/gʊd/" },
      { text: "again", ipa: "/əˈgɛn/" },
      { text: "bag", ipa: "/bæg/" },
    ],
    minimalPairs: [
      { left: "goat", leftIpa: "/goʊt/", right: "coat", rightIpa: "/koʊt/" },
      { left: "game", leftIpa: "/geɪm/", right: "came", rightIpa: "/keɪm/" },
      { left: "bag", leftIpa: "/bæg/", right: "back", rightIpa: "/bæk/" },
    ],
    sentences: ["Gary got a good grade."],
    commonMistake: "Final /g/ may sound like /k/ when voicing is lost.",
    correctionTip: "Keep the vowel before /g/ a little longer and keep vibration.",
    practiceDrill: "Repeat: go, good, again, big, bag.",
    homework: "Record final /g/ words and compare them with final /k/ words.",
  },
  {
    id: "f",
    group: "consonants",
    ipa: "/f/",
    title: "/f/ as in fine",
    example: { text: "fine", ipa: "/faɪn/" },
    audioText: "f. fine. Five friends found fresh fruit.",
    soundType: "Voiceless fricative consonant",
    hint: "Touch the top teeth to the lower lip and blow air.",
    mouthPosition: "Rest the top teeth on the lower lip. Let air pass continuously. Do not voice.",
    spellings: ["f: fine", "ff: coffee", "ph: phone", "gh: laugh"],
    words: [
      { text: "fine", ipa: "/faɪn/" },
      { text: "coffee", ipa: "/ˈkɑfi/" },
      { text: "phone", ipa: "/foʊn/" },
      { text: "laugh", ipa: "/læf/" },
    ],
    minimalPairs: [
      { left: "fan", leftIpa: "/fæn/", right: "van", rightIpa: "/væn/" },
      { left: "safe", leftIpa: "/seɪf/", right: "save", rightIpa: "/seɪv/" },
      { left: "fine", leftIpa: "/faɪn/", right: "vine", rightIpa: "/vaɪn/" },
    ],
    sentences: ["Five friends found fresh fruit."],
    commonMistake: "Some learners use /p/ instead of /f/ because the lips close fully.",
    correctionTip: "Keep a small air path between teeth and lip; do not close both lips.",
    practiceDrill: "Hold /f/ for two seconds: fff. Then say fine, coffee, phone.",
    homework: "Find five ph words and five f words. Pronounce them the same way.",
  },
  {
    id: "v",
    group: "consonants",
    ipa: "/v/",
    title: "/v/ as in voice",
    example: { text: "voice", ipa: "/vɔɪs/" },
    audioText: "v. voice. Victor has a very vivid voice.",
    soundType: "Voiced fricative consonant",
    hint: "Use teeth and lower lip like /f/, but add voice.",
    mouthPosition: "Top teeth touch the lower lip. Air passes continuously while the vocal cords vibrate.",
    spellings: ["v: voice", "ve: have"],
    words: [
      { text: "voice", ipa: "/vɔɪs/" },
      { text: "very", ipa: "/ˈvɛri/" },
      { text: "seven", ipa: "/ˈsɛvən/" },
      { text: "have", ipa: "/hæv/" },
    ],
    minimalPairs: [
      { left: "van", leftIpa: "/væn/", right: "fan", rightIpa: "/fæn/" },
      { left: "save", leftIpa: "/seɪv/", right: "safe", rightIpa: "/seɪf/" },
      { left: "vine", leftIpa: "/vaɪn/", right: "fine", rightIpa: "/faɪn/" },
    ],
    sentences: ["Victor has a very vivid voice."],
    commonMistake: "Final /v/ may become /f/, especially in have and live.",
    correctionTip: "Keep vibration until the end of the word.",
    practiceDrill: "Alternate: fff, vvv. Then fan, van; safe, save.",
    homework: "Record five sentences with have and of pronounced clearly.",
  },
  {
    id: "theta",
    group: "consonants",
    ipa: "/θ/",
    title: "/θ/ as in think",
    example: { text: "think", ipa: "/θɪŋk/" },
    audioText: "th. think. I think three things are helpful.",
    soundType: "Voiceless dental fricative consonant",
    hint: "Tongue gently between the teeth. Blow air. No voice.",
    mouthPosition: "Place the tongue tip lightly between the teeth. Let air pass over the tongue without vibration.",
    spellings: ["th: think, three, both"],
    words: [
      { text: "think", ipa: "/θɪŋk/" },
      { text: "three", ipa: "/θri/" },
      { text: "author", ipa: "/ˈɔθɚ/" },
      { text: "both", ipa: "/boʊθ/" },
    ],
    minimalPairs: [
      { left: "thin", leftIpa: "/θɪn/", right: "sin", rightIpa: "/sɪn/" },
      { left: "think", leftIpa: "/θɪŋk/", right: "sink", rightIpa: "/sɪŋk/" },
      { left: "three", leftIpa: "/θri/", right: "tree", rightIpa: "/tri/" },
    ],
    sentences: ["I think three things are helpful."],
    commonMistake: "Learners often replace /θ/ with /s/, /t/, or /f/.",
    correctionTip: "Let the tongue be visible for a moment and keep the air flowing.",
    practiceDrill: "Repeat slowly: th, th, think, three, both.",
    homework: "Practice ten common th words in front of a mirror.",
  },
  {
    id: "eth",
    group: "consonants",
    ipa: "/ð/",
    title: "/ð/ as in this",
    example: { text: "this", ipa: "/ðɪs/" },
    audioText: "th. this. This weather is better than that.",
    soundType: "Voiced dental fricative consonant",
    hint: "Tongue gently between the teeth with voice.",
    mouthPosition: "Place the tongue tip lightly between the teeth. Let air pass while the vocal cords vibrate.",
    spellings: ["th: this, that, mother"],
    words: [
      { text: "this", ipa: "/ðɪs/" },
      { text: "that", ipa: "/ðæt/" },
      { text: "mother", ipa: "/ˈmʌðɚ/" },
      { text: "breathe", ipa: "/brið/" },
    ],
    minimalPairs: [
      { left: "then", leftIpa: "/ðɛn/", right: "den", rightIpa: "/dɛn/" },
      { left: "they", leftIpa: "/ðeɪ/", right: "day", rightIpa: "/deɪ/" },
      { left: "breathe", leftIpa: "/brið/", right: "brief", rightIpa: "/brif/" },
    ],
    sentences: ["This weather is better than that."],
    commonMistake: "Learners often replace /ð/ with /d/, /z/, or /v/.",
    correctionTip: "Keep the tongue between the teeth and add a soft buzz.",
    practiceDrill: "Alternate: θ, ð. Then: thin, then; thigh, thy.",
    homework: "Practice function words: the, this, that, these, those, they.",
  },
  {
    id: "s",
    group: "consonants",
    ipa: "/s/",
    title: "/s/ as in see",
    example: { text: "see", ipa: "/si/" },
    audioText: "s. see. Sam saw six small signs.",
    soundType: "Voiceless fricative consonant",
    hint: "Smile lightly and send air through a narrow tongue groove.",
    mouthPosition: "Keep the tongue close to the alveolar ridge without touching. Let air hiss through.",
    spellings: ["s: see", "ss: class", "c: city", "ce: face"],
    words: [
      { text: "see", ipa: "/si/" },
      { text: "city", ipa: "/ˈsɪti/" },
      { text: "lesson", ipa: "/ˈlɛsən/" },
      { text: "face", ipa: "/feɪs/" },
    ],
    minimalPairs: [
      { left: "sip", leftIpa: "/sɪp/", right: "zip", rightIpa: "/zɪp/" },
      { left: "ice", leftIpa: "/aɪs/", right: "eyes", rightIpa: "/aɪz/" },
      { left: "sink", leftIpa: "/sɪŋk/", right: "think", rightIpa: "/θɪŋk/" },
    ],
    sentences: ["Sam saw six small signs."],
    commonMistake: "Learners may add voice and pronounce final /s/ as /z/.",
    correctionTip: "Keep the throat quiet and let the air hiss.",
    practiceDrill: "Hold /s/: sss. Then read: see, city, class, face.",
    homework: "Sort ten plural words into /s/, /z/, and /ɪz/ endings.",
  },
  {
    id: "z",
    group: "consonants",
    ipa: "/z/",
    title: "/z/ as in zoo",
    example: { text: "zoo", ipa: "/zu/" },
    audioText: "z. zoo. Zoe uses these amazing words.",
    soundType: "Voiced fricative consonant",
    hint: "Make the /s/ shape and add voice.",
    mouthPosition: "Keep a narrow air channel near the alveolar ridge and vibrate the vocal cords.",
    spellings: ["z: zoo", "s: is", "zz: buzz", "x: example"],
    words: [
      { text: "zoo", ipa: "/zu/" },
      { text: "zero", ipa: "/ˈziroʊ/" },
      { text: "music", ipa: "/ˈmjuzɪk/" },
      { text: "buzz", ipa: "/bʌz/" },
    ],
    minimalPairs: [
      { left: "zip", leftIpa: "/zɪp/", right: "sip", rightIpa: "/sɪp/" },
      { left: "eyes", leftIpa: "/aɪz/", right: "ice", rightIpa: "/aɪs/" },
      { left: "rise", leftIpa: "/raɪz/", right: "rice", rightIpa: "/raɪs/" },
    ],
    sentences: ["Zoe uses these amazing words."],
    commonMistake: "Final /z/ may become /s/, especially in plurals and third-person verbs.",
    correctionTip: "Keep the vibration through the ending: dogs, plays, learns.",
    practiceDrill: "Alternate: sss, zzz. Then ice, eyes; bus, buzz.",
    homework: "Read twenty words ending in voiced consonants plus -s.",
  },
  {
    id: "sh",
    group: "consonants",
    ipa: "/ʃ/",
    title: "/ʃ/ as in she",
    example: { text: "she", ipa: "/ʃi/" },
    audioText: "sh. she. She showed Sharon the short sheet.",
    soundType: "Voiceless postalveolar fricative consonant",
    hint: "Round the lips slightly and push air over the middle of the tongue.",
    mouthPosition: "Raise the front-middle of the tongue behind the alveolar ridge. Keep the voice off.",
    spellings: ["sh: she", "ti: nation", "ci: special", "ss: pressure"],
    words: [
      { text: "she", ipa: "/ʃi/" },
      { text: "ship", ipa: "/ʃɪp/" },
      { text: "nation", ipa: "/ˈneɪʃən/" },
      { text: "wash", ipa: "/wɑʃ/" },
    ],
    minimalPairs: [
      { left: "ship", leftIpa: "/ʃɪp/", right: "sip", rightIpa: "/sɪp/" },
      { left: "she", leftIpa: "/ʃi/", right: "see", rightIpa: "/si/" },
      { left: "cash", leftIpa: "/kæʃ/", right: "catch", rightIpa: "/kætʃ/" },
    ],
    sentences: ["She showed Sharon the short sheet."],
    commonMistake: "Learners may pronounce /ʃ/ as /s/ because the tongue is too far forward.",
    correctionTip: "Pull the sound slightly back and add gentle lip rounding.",
    practiceDrill: "Repeat: she, ship, wash, special, nation.",
    homework: "Practice five words with sh and five words with ti pronounced /ʃ/.",
  },
  {
    id: "zh",
    group: "consonants",
    ipa: "/ʒ/",
    title: "/ʒ/ as in measure",
    example: { text: "measure", ipa: "/ˈmɛʒɚ/" },
    audioText: "zh. measure. The usual decision was a pleasure.",
    soundType: "Voiced postalveolar fricative consonant",
    hint: "Use the /ʃ/ shape with voice.",
    mouthPosition: "Raise the middle-front tongue behind the ridge, round the lips slightly, and vibrate.",
    spellings: ["s: measure", "si: vision", "g: genre"],
    words: [
      { text: "measure", ipa: "/ˈmɛʒɚ/" },
      { text: "vision", ipa: "/ˈvɪʒən/" },
      { text: "usual", ipa: "/ˈjuʒuəl/" },
      { text: "garage", ipa: "/gəˈrɑʒ/" },
    ],
    minimalPairs: [
      { left: "measure", leftIpa: "/ˈmɛʒɚ/", right: "mesher", rightIpa: "/ˈmɛʃɚ/" },
      { left: "vision", leftIpa: "/ˈvɪʒən/", right: "mission", rightIpa: "/ˈmɪʃən/" },
      { left: "genre", leftIpa: "/ˈʒɑnrə/", right: "shah", rightIpa: "/ʃɑ/" },
    ],
    sentences: ["The usual decision was a pleasure."],
    commonMistake: "Learners often replace /ʒ/ with /ʃ/, /z/, or /dʒ/.",
    correctionTip: "Start from /ʃ/, add voice, and avoid a full stop before it.",
    practiceDrill: "Repeat: vision, usual, measure, pleasure.",
    homework: "Record the words decision, usually, visual, and measure in sentences.",
  },
  {
    id: "h",
    group: "consonants",
    ipa: "/h/",
    title: "/h/ as in happy",
    example: { text: "happy", ipa: "/ˈhæpi/" },
    audioText: "h. happy. Hannah has a happy home.",
    soundType: "Voiceless glottal fricative consonant",
    hint: "Breathe out gently before the vowel.",
    mouthPosition: "Keep the mouth ready for the next vowel and release a light breath from the throat.",
    spellings: ["h: happy", "wh: who"],
    words: [
      { text: "happy", ipa: "/ˈhæpi/" },
      { text: "home", ipa: "/hoʊm/" },
      { text: "ahead", ipa: "/əˈhɛd/" },
      { text: "who", ipa: "/hu/" },
    ],
    minimalPairs: [
      { left: "heat", leftIpa: "/hit/", right: "eat", rightIpa: "/it/" },
      { left: "hill", leftIpa: "/hɪl/", right: "ill", rightIpa: "/ɪl/" },
      { left: "hold", leftIpa: "/hoʊld/", right: "old", rightIpa: "/oʊld/" },
    ],
    sentences: ["Hannah has a happy home."],
    commonMistake: "Some learners drop /h/ or add /h/ before vowel-initial words.",
    correctionTip: "Use /h/ only when the spelling and word require it.",
    practiceDrill: "Alternate: heat, eat; hill, ill; hold, old.",
    homework: "Read a paragraph and underline every pronounced h.",
  },
  {
    id: "ch",
    group: "consonants",
    ipa: "/tʃ/",
    title: "/tʃ/ as in chair",
    example: { text: "chair", ipa: "/tʃɛr/" },
    audioText: "ch. chair. Charlie chose a cheap chair.",
    soundType: "Voiceless affricate consonant",
    hint: "Start like /t/ and release into /ʃ/.",
    mouthPosition: "Touch near the alveolar ridge, stop the air, then release into a short /ʃ/ sound.",
    spellings: ["ch: chair", "tch: watch", "tu: nature"],
    words: [
      { text: "chair", ipa: "/tʃɛr/" },
      { text: "choose", ipa: "/tʃuz/" },
      { text: "teacher", ipa: "/ˈtitʃɚ/" },
      { text: "watch", ipa: "/wɑtʃ/" },
    ],
    minimalPairs: [
      { left: "cheap", leftIpa: "/tʃip/", right: "sheep", rightIpa: "/ʃip/" },
      { left: "chop", leftIpa: "/tʃɑp/", right: "shop", rightIpa: "/ʃɑp/" },
      { left: "watch", leftIpa: "/wɑtʃ/", right: "wash", rightIpa: "/wɑʃ/" },
    ],
    sentences: ["Charlie chose a cheap chair."],
    commonMistake: "Learners may pronounce /tʃ/ as /ʃ/ by missing the stop.",
    correctionTip: "Begin with a clear /t/ closure before the release.",
    practiceDrill: "Repeat: t + sh = ch. Then cheap, chair, watch.",
    homework: "Practice ten words spelled ch and tch.",
  },
  {
    id: "j",
    group: "consonants",
    ipa: "/dʒ/",
    title: "/dʒ/ as in job",
    example: { text: "job", ipa: "/dʒɑb/" },
    audioText: "j. job. Jane enjoys her new job.",
    soundType: "Voiced affricate consonant",
    hint: "Start like /d/ and release into /ʒ/ with voice.",
    mouthPosition: "Touch near the alveolar ridge, stop the air, and release with vocal vibration.",
    spellings: ["j: job", "g: giant", "ge: age", "dg: judge"],
    words: [
      { text: "job", ipa: "/dʒɑb/" },
      { text: "June", ipa: "/dʒun/" },
      { text: "giant", ipa: "/ˈdʒaɪənt/" },
      { text: "judge", ipa: "/dʒʌdʒ/" },
    ],
    minimalPairs: [
      { left: "job", leftIpa: "/dʒɑb/", right: "chop", rightIpa: "/tʃɑp/" },
      { left: "gin", leftIpa: "/dʒɪn/", right: "chin", rightIpa: "/tʃɪn/" },
      { left: "ridge", leftIpa: "/rɪdʒ/", right: "rich", rightIpa: "/rɪtʃ/" },
    ],
    sentences: ["Jane enjoys her new job."],
    commonMistake: "Final /dʒ/ may lose voice or become /ʃ/.",
    correctionTip: "Keep the voiced stop before the release: judge, age, large.",
    practiceDrill: "Repeat: d + zh = j. Then job, giant, age.",
    homework: "Collect ten words where g is pronounced /dʒ/.",
  },
  {
    id: "m",
    group: "consonants",
    ipa: "/m/",
    title: "/m/ as in man",
    example: { text: "man", ipa: "/mæn/" },
    audioText: "m. man. My mother made more memories.",
    soundType: "Voiced nasal consonant",
    hint: "Close both lips and send voice through the nose.",
    mouthPosition: "Close the lips. Let air flow through the nose while the vocal cords vibrate.",
    spellings: ["m: man", "mm: summer", "mb: climb"],
    words: [
      { text: "man", ipa: "/mæn/" },
      { text: "mother", ipa: "/ˈmʌðɚ/" },
      { text: "summer", ipa: "/ˈsʌmɚ/" },
      { text: "time", ipa: "/taɪm/" },
    ],
    minimalPairs: [
      { left: "mat", leftIpa: "/mæt/", right: "bat", rightIpa: "/bæt/" },
      { left: "sum", leftIpa: "/sʌm/", right: "sun", rightIpa: "/sʌn/" },
      { left: "ram", leftIpa: "/ræm/", right: "ran", rightIpa: "/ræn/" },
    ],
    sentences: ["My mother made more memories."],
    commonMistake: "Final /m/ can become unclear if the lips do not close.",
    correctionTip: "Finish with closed lips and a short nasal hum.",
    practiceDrill: "Hum /m/ for one second. Then man, mother, time.",
    homework: "Read five sentences and hold every final /m/ briefly.",
  },
  {
    id: "n",
    group: "consonants",
    ipa: "/n/",
    title: "/n/ as in night",
    example: { text: "night", ipa: "/naɪt/" },
    audioText: "n. night. Nina needs nine new notebooks.",
    soundType: "Voiced nasal consonant",
    hint: "Touch the ridge behind the teeth and send voice through the nose.",
    mouthPosition: "Put the tongue tip on the alveolar ridge. Let air flow through the nose with voice.",
    spellings: ["n: night", "nn: dinner", "kn: know"],
    words: [
      { text: "night", ipa: "/naɪt/" },
      { text: "new", ipa: "/nu/" },
      { text: "dinner", ipa: "/ˈdɪnɚ/" },
      { text: "sun", ipa: "/sʌn/" },
    ],
    minimalPairs: [
      { left: "no", leftIpa: "/noʊ/", right: "go", rightIpa: "/goʊ/" },
      { left: "sun", leftIpa: "/sʌn/", right: "sum", rightIpa: "/sʌm/" },
      { left: "ran", leftIpa: "/ræn/", right: "rang", rightIpa: "/ræŋ/" },
    ],
    sentences: ["Nina needs nine new notebooks."],
    commonMistake: "Learners may confuse final /n/ and /ŋ/.",
    correctionTip: "For /n/, the tongue tip touches behind the teeth.",
    practiceDrill: "Alternate: sun, sung; ran, rang; sin, sing.",
    homework: "Record final n words and check that your tongue tip touches the ridge.",
  },
  {
    id: "ng",
    group: "consonants",
    ipa: "/ŋ/",
    title: "/ŋ/ as in sing",
    example: { text: "sing", ipa: "/sɪŋ/" },
    audioText: "ng. sing. We are singing a long song.",
    soundType: "Voiced velar nasal consonant",
    hint: "Raise the back of the tongue and send voice through the nose.",
    mouthPosition: "Lift the back of the tongue to the soft palate. Keep the tongue tip down.",
    spellings: ["ng: sing", "n before k/g: bank, finger"],
    words: [
      { text: "sing", ipa: "/sɪŋ/" },
      { text: "long", ipa: "/lɔŋ/" },
      { text: "bank", ipa: "/bæŋk/" },
      { text: "finger", ipa: "/ˈfɪŋgɚ/" },
    ],
    minimalPairs: [
      { left: "sing", leftIpa: "/sɪŋ/", right: "sin", rightIpa: "/sɪn/" },
      { left: "rang", leftIpa: "/ræŋ/", right: "ran", rightIpa: "/ræn/" },
      { left: "sung", leftIpa: "/sʌŋ/", right: "sun", rightIpa: "/sʌn/" },
    ],
    sentences: ["We are singing a long song."],
    commonMistake: "Learners may add a hard /g/ at the end: sing-g.",
    correctionTip: "In common -ing endings, finish with /ŋ/ and no extra /g/.",
    practiceDrill: "Repeat: sing, singing, long, song, bank.",
    homework: "Read ten -ing verbs and keep the tongue tip down.",
  },
  {
    id: "l",
    group: "consonants",
    ipa: "/l/",
    title: "/l/ as in light",
    example: { text: "light", ipa: "/laɪt/" },
    audioText: "l. light. Lily likes learning long lessons.",
    soundType: "Voiced lateral consonant",
    hint: "Touch the ridge with the tongue tip and let air pass around the sides.",
    mouthPosition: "Place the tongue tip on the alveolar ridge. Let the voice continue around the sides of the tongue.",
    spellings: ["l: light", "ll: yellow"],
    words: [
      { text: "light", ipa: "/laɪt/" },
      { text: "lesson", ipa: "/ˈlɛsən/" },
      { text: "yellow", ipa: "/ˈjɛloʊ/" },
      { text: "feel", ipa: "/fil/" },
    ],
    minimalPairs: [
      { left: "light", leftIpa: "/laɪt/", right: "right", rightIpa: "/raɪt/" },
      { left: "lock", leftIpa: "/lɑk/", right: "rock", rightIpa: "/rɑk/" },
      { left: "feel", leftIpa: "/fil/", right: "fear", rightIpa: "/fɪr/" },
    ],
    sentences: ["Lily likes learning long lessons."],
    commonMistake: "Learners may confuse /l/ and /r/ or make final /l/ too vowel-like.",
    correctionTip: "For clear /l/, touch the ridge with the tongue tip.",
    practiceDrill: "Alternate: light, right; lock, rock; late, rate.",
    homework: "Practice ten initial /l/ words and ten final /l/ words.",
  },
  {
    id: "r",
    group: "consonants",
    ipa: "/r/",
    title: "/r/ as in red",
    example: { text: "red", ipa: "/rɛd/" },
    audioText: "r. red. Rachel read the red report.",
    soundType: "Voiced approximant consonant",
    hint: "Pull the tongue back slightly; do not touch the ridge.",
    mouthPosition: "Raise and pull the tongue back. Keep the sides lifted and the center open. Round the lips slightly if helpful.",
    spellings: ["r: red", "rr: sorry", "wr: write"],
    words: [
      { text: "red", ipa: "/rɛd/" },
      { text: "right", ipa: "/raɪt/" },
      { text: "sorry", ipa: "/ˈsɑri/" },
      { text: "car", ipa: "/kɑr/" },
    ],
    minimalPairs: [
      { left: "right", leftIpa: "/raɪt/", right: "light", rightIpa: "/laɪt/" },
      { left: "rock", leftIpa: "/rɑk/", right: "lock", rightIpa: "/lɑk/" },
      { left: "fear", leftIpa: "/fɪr/", right: "feel", rightIpa: "/fil/" },
    ],
    sentences: ["Rachel read the red report."],
    commonMistake: "Learners may make /r/ like /l/, a trill, or a vowel.",
    correctionTip: "Keep the tongue from tapping or touching. Hold a steady American /r/ shape.",
    practiceDrill: "Repeat: red, right, around, car, teacher.",
    homework: "Record yourself saying car, hard, bird, and teacher in sentences.",
  },
  {
    id: "y",
    group: "consonants",
    ipa: "/j/",
    title: "/j/ as in yes",
    example: { text: "yes", ipa: "/jɛs/" },
    audioText: "y. yes. Yes, young students use English.",
    soundType: "Voiced palatal approximant consonant",
    hint: "Start like the vowel /i/ and glide into the next vowel.",
    mouthPosition: "Raise the front of the tongue near the hard palate, then glide quickly into the vowel.",
    spellings: ["y: yes", "u: use", "eau: beauty"],
    words: [
      { text: "yes", ipa: "/jɛs/" },
      { text: "you", ipa: "/ju/" },
      { text: "use", ipa: "/juz/" },
      { text: "beyond", ipa: "/biˈjɑnd/" },
    ],
    minimalPairs: [
      { left: "yes", leftIpa: "/jɛs/", right: "less", rightIpa: "/lɛs/" },
      { left: "yell", leftIpa: "/jɛl/", right: "well", rightIpa: "/wɛl/" },
      { left: "year", leftIpa: "/jɪr/", right: "ear", rightIpa: "/ɪr/" },
    ],
    sentences: ["Yes, young students use English."],
    commonMistake: "Learners may drop /j/ in words like use or year.",
    correctionTip: "Begin with a quick /i/ glide before the vowel.",
    practiceDrill: "Repeat: yes, you, year, use, beyond.",
    homework: "Practice five sentences with you, your, year, and use.",
  },
  {
    id: "w",
    group: "consonants",
    ipa: "/w/",
    title: "/w/ as in water",
    example: { text: "water", ipa: "/ˈwɑtɚ/" },
    audioText: "w. water. We will watch the warm water.",
    soundType: "Voiced labiovelar approximant consonant",
    hint: "Round the lips and glide into the vowel.",
    mouthPosition: "Round the lips tightly, raise the back of the tongue slightly, then open into the vowel.",
    spellings: ["w: water", "wh: when", "u: quick", "o: one"],
    words: [
      { text: "water", ipa: "/ˈwɑtɚ/" },
      { text: "we", ipa: "/wi/" },
      { text: "quick", ipa: "/kwɪk/" },
      { text: "one", ipa: "/wʌn/" },
    ],
    minimalPairs: [
      { left: "wet", leftIpa: "/wɛt/", right: "vet", rightIpa: "/vɛt/" },
      { left: "wine", leftIpa: "/waɪn/", right: "vine", rightIpa: "/vaɪn/" },
      { left: "west", leftIpa: "/wɛst/", right: "best", rightIpa: "/bɛst/" },
    ],
    sentences: ["We will watch the warm water."],
    commonMistake: "Learners may pronounce /w/ like /v/ if the teeth touch the lip.",
    correctionTip: "Round both lips. Do not touch the teeth to the lower lip.",
    practiceDrill: "Alternate: wet, vet; wine, vine; west, vest.",
    homework: "Record ten words beginning with w and check for lip rounding.",
  },
];

export const vowelLessons: SoundLesson[] = [
  {
    id: "i",
    group: "vowels",
    ipa: "/i/",
    title: "/i/ as in see",
    example: { text: "see", ipa: "/si/" },
    audioText: "ee. see. We need three clean sheets.",
    soundType: "High front tense vowel",
    hint: "Smile lightly, tongue high and forward, long clear vowel.",
    mouthPosition: "Keep the jaw fairly closed. Move the tongue high and forward. Spread the lips slightly.",
    spellings: ["ee: see", "ea: speak", "e: me", "ie: field"],
    words: [
      { text: "see", ipa: "/si/" },
      { text: "need", ipa: "/nid/" },
      { text: "teacher", ipa: "/ˈtitʃɚ/" },
      { text: "green", ipa: "/grin/" },
    ],
    minimalPairs: [
      { left: "sheep", leftIpa: "/ʃip/", right: "ship", rightIpa: "/ʃɪp/" },
      { left: "seat", leftIpa: "/sit/", right: "sit", rightIpa: "/sɪt/" },
      { left: "leave", leftIpa: "/liv/", right: "live", rightIpa: "/lɪv/" },
    ],
    sentences: ["We need three clean sheets."],
    commonMistake: "Learners may shorten /i/ and make it sound like /ɪ/.",
    correctionTip: "Hold the vowel a little longer and keep the tongue high.",
    practiceDrill: "Repeat: see, seat, sheep, green, teacher.",
    homework: "Record minimal pairs with /i/ and /ɪ/ and compare vowel length.",
  },
  {
    id: "ih",
    group: "vowels",
    ipa: "/ɪ/",
    title: "/ɪ/ as in sit",
    example: { text: "sit", ipa: "/sɪt/" },
    audioText: "ih. sit. This little dish is delicious.",
    soundType: "High front lax vowel",
    hint: "Short, relaxed vowel. Tongue is high, but lower than /i/.",
    mouthPosition: "Relax the lips and jaw. Keep the tongue near the front but not as high or tense as /i/.",
    spellings: ["i: sit", "y: gym", "ui: build", "e: pretty"],
    words: [
      { text: "sit", ipa: "/sɪt/" },
      { text: "little", ipa: "/ˈlɪtəl/" },
      { text: "build", ipa: "/bɪld/" },
      { text: "pretty", ipa: "/ˈprɪti/" },
    ],
    minimalPairs: [
      { left: "ship", leftIpa: "/ʃɪp/", right: "sheep", rightIpa: "/ʃip/" },
      { left: "sit", leftIpa: "/sɪt/", right: "seat", rightIpa: "/sit/" },
      { left: "live", leftIpa: "/lɪv/", right: "leave", rightIpa: "/liv/" },
    ],
    sentences: ["This little dish is delicious."],
    commonMistake: "Learners often pronounce /ɪ/ too tense, like /i/.",
    correctionTip: "Relax the vowel. Do not smile too much or hold it too long.",
    practiceDrill: "Repeat: sit, six, little, build, pretty.",
    homework: "Practice /ɪ/ words in short sentences with a relaxed jaw.",
  },
  {
    id: "eɪ",
    group: "vowels",
    ipa: "/eɪ/",
    title: "/eɪ/ as in day",
    example: { text: "day", ipa: "/deɪ/" },
    audioText: "ay. day. They stayed late today.",
    soundType: "Front closing diphthong",
    hint: "Start at /e/ and glide gently toward /ɪ/.",
    mouthPosition: "Begin with a mid-front tongue position and move upward slightly as the sound finishes.",
    spellings: ["a_e: name", "ai: rain", "ay: day", "ei: eight"],
    words: [
      { text: "day", ipa: "/deɪ/" },
      { text: "name", ipa: "/neɪm/" },
      { text: "rain", ipa: "/reɪn/" },
      { text: "eight", ipa: "/eɪt/" },
    ],
    minimalPairs: [
      { left: "late", leftIpa: "/leɪt/", right: "let", rightIpa: "/lɛt/" },
      { left: "main", leftIpa: "/meɪn/", right: "men", rightIpa: "/mɛn/" },
      { left: "made", leftIpa: "/meɪd/", right: "mad", rightIpa: "/mæd/" },
    ],
    sentences: ["They stayed late today."],
    commonMistake: "Learners may pronounce /eɪ/ as a flat /ɛ/ or /æ/.",
    correctionTip: "Add the small upward glide at the end: day, name, late.",
    practiceDrill: "Repeat: day, say, rain, name, late.",
    homework: "Read ten a_e words and ten ai/ay words aloud.",
  },
  {
    id: "eh",
    group: "vowels",
    ipa: "/ɛ/",
    title: "/ɛ/ as in pen",
    example: { text: "pen", ipa: "/pɛn/" },
    audioText: "eh. pen. Ben left ten red pens.",
    soundType: "Mid front lax vowel",
    hint: "Short open vowel, like a relaxed smile.",
    mouthPosition: "Open the jaw slightly. Keep the tongue front and mid-low. Lips are relaxed.",
    spellings: ["e: pen", "ea: bread", "ai: said", "ie: friend"],
    words: [
      { text: "pen", ipa: "/pɛn/" },
      { text: "red", ipa: "/rɛd/" },
      { text: "bread", ipa: "/brɛd/" },
      { text: "friend", ipa: "/frɛnd/" },
    ],
    minimalPairs: [
      { left: "pen", leftIpa: "/pɛn/", right: "pan", rightIpa: "/pæn/" },
      { left: "bed", leftIpa: "/bɛd/", right: "bad", rightIpa: "/bæd/" },
      { left: "let", leftIpa: "/lɛt/", right: "late", rightIpa: "/leɪt/" },
    ],
    sentences: ["Ben left ten red pens."],
    commonMistake: "Learners may confuse /ɛ/ with /æ/ or /eɪ/.",
    correctionTip: "Keep it short and centered between /ɪ/ and /æ/.",
    practiceDrill: "Repeat: pen, ten, red, bread, friend.",
    homework: "Practice pen/pan and bed/bad minimal pairs.",
  },
  {
    id: "ae",
    group: "vowels",
    ipa: "/æ/",
    title: "/æ/ as in cat",
    example: { text: "cat", ipa: "/kæt/" },
    audioText: "aa. cat. That black cat sat on the mat.",
    soundType: "Low front vowel",
    hint: "Open the mouth wider than /ɛ/ and keep the tongue forward.",
    mouthPosition: "Open the jaw. Keep the tongue low-front. The lips stay relaxed and unrounded.",
    spellings: ["a: cat, map, happy"],
    words: [
      { text: "cat", ipa: "/kæt/" },
      { text: "map", ipa: "/mæp/" },
      { text: "happy", ipa: "/ˈhæpi/" },
      { text: "back", ipa: "/bæk/" },
    ],
    minimalPairs: [
      { left: "pan", leftIpa: "/pæn/", right: "pen", rightIpa: "/pɛn/" },
      { left: "bad", leftIpa: "/bæd/", right: "bed", rightIpa: "/bɛd/" },
      { left: "sat", leftIpa: "/sæt/", right: "set", rightIpa: "/sɛt/" },
    ],
    sentences: ["That black cat sat on the mat."],
    commonMistake: "Learners may make /æ/ too close to /ɛ/.",
    correctionTip: "Open the jaw more and keep the vowel short.",
    practiceDrill: "Repeat: cat, map, back, happy, black.",
    homework: "Record /æ/ words and check that the mouth opens enough.",
  },
  {
    id: "ah",
    group: "vowels",
    ipa: "/ɑ/",
    title: "/ɑ/ as in hot",
    example: { text: "hot", ipa: "/hɑt/" },
    audioText: "ah. hot. Tom got a hot cup of coffee.",
    soundType: "Low back unrounded vowel",
    hint: "Open the jaw and keep lips unrounded.",
    mouthPosition: "Drop the jaw. Keep the tongue low and back. Do not round the lips.",
    spellings: ["o: hot", "a: father", "al: calm"],
    words: [
      { text: "hot", ipa: "/hɑt/" },
      { text: "father", ipa: "/ˈfɑðɚ/" },
      { text: "coffee", ipa: "/ˈkɑfi/" },
      { text: "calm", ipa: "/kɑm/" },
    ],
    minimalPairs: [
      { left: "cot", leftIpa: "/kɑt/", right: "cat", rightIpa: "/kæt/" },
      { left: "hot", leftIpa: "/hɑt/", right: "hut", rightIpa: "/hʌt/" },
      { left: "lock", leftIpa: "/lɑk/", right: "luck", rightIpa: "/lʌk/" },
    ],
    sentences: ["Tom got a hot cup of coffee."],
    commonMistake: "Learners may round the lips or use British /ɒ/.",
    correctionTip: "For American English, keep the lips relaxed and unrounded: hot /hɑt/.",
    practiceDrill: "Repeat: hot, coffee, father, calm, lock.",
    homework: "Practice hot, car, father, and hard with American rhotic vowels where needed.",
  },
  {
    id: "aw",
    group: "vowels",
    ipa: "/ɔ/",
    title: "/ɔ/ as in thought",
    example: { text: "thought", ipa: "/θɔt/" },
    audioText: "aw. thought. Paul bought a small ball.",
    soundType: "Mid-low back rounded vowel",
    hint: "Round the lips and keep the tongue back.",
    mouthPosition: "Lower the jaw slightly, move the tongue back, and round the lips.",
    spellings: ["aw: saw", "au: author", "ought: thought", "all: ball"],
    words: [
      { text: "thought", ipa: "/θɔt/" },
      { text: "saw", ipa: "/sɔ/" },
      { text: "author", ipa: "/ˈɔθɚ/" },
      { text: "ball", ipa: "/bɔl/" },
    ],
    minimalPairs: [
      { left: "caught", leftIpa: "/kɔt/", right: "cot", rightIpa: "/kɑt/" },
      { left: "dawn", leftIpa: "/dɔn/", right: "Don", rightIpa: "/dɑn/" },
      { left: "law", leftIpa: "/lɔ/", right: "low", rightIpa: "/loʊ/" },
    ],
    sentences: ["Paul bought a small ball."],
    commonMistake: "Many American accents merge /ɔ/ and /ɑ/, but learners should recognize both symbols.",
    correctionTip: "When distinct, /ɔ/ has more lip rounding than /ɑ/.",
    practiceDrill: "Repeat: saw, thought, author, ball, caught.",
    homework: "Practice /ɔ/ and /ɑ/ pairs if your target accent keeps them distinct.",
  },
  {
    id: "oʊ",
    group: "vowels",
    ipa: "/oʊ/",
    title: "/oʊ/ as in go",
    example: { text: "go", ipa: "/goʊ/" },
    audioText: "oh. go. Don't go home alone.",
    soundType: "Back closing diphthong",
    hint: "Start rounded and glide upward; American English uses /oʊ/.",
    mouthPosition: "Begin with rounded lips and a mid-back tongue. Glide toward /ʊ/ as the vowel ends.",
    spellings: ["o: go", "oa: road", "ow: show", "oe: toe"],
    words: [
      { text: "go", ipa: "/goʊ/" },
      { text: "home", ipa: "/hoʊm/" },
      { text: "road", ipa: "/roʊd/" },
      { text: "show", ipa: "/ʃoʊ/" },
    ],
    minimalPairs: [
      { left: "go", leftIpa: "/goʊ/", right: "gaw", rightIpa: "/gɔ/" },
      { left: "coat", leftIpa: "/koʊt/", right: "caught", rightIpa: "/kɔt/" },
      { left: "low", leftIpa: "/loʊ/", right: "law", rightIpa: "/lɔ/" },
    ],
    sentences: ["Don't go home alone."],
    commonMistake: "Learners may use British /əʊ/ or make the vowel too flat.",
    correctionTip: "Start with clear lip rounding and finish with a small /ʊ/ glide.",
    practiceDrill: "Repeat: go, home, road, show, alone.",
    homework: "Record ten words spelled o, oa, and ow with /oʊ/.",
  },
  {
    id: "uh",
    group: "vowels",
    ipa: "/ʊ/",
    title: "/ʊ/ as in book",
    example: { text: "book", ipa: "/bʊk/" },
    audioText: "uh. book. Look at the good cookbook.",
    soundType: "High back lax rounded vowel",
    hint: "Short rounded vowel, relaxed and not as long as /u/.",
    mouthPosition: "Round the lips lightly. Keep the tongue high-back but relaxed.",
    spellings: ["oo: book", "u: put", "oul: could"],
    words: [
      { text: "book", ipa: "/bʊk/" },
      { text: "good", ipa: "/gʊd/" },
      { text: "put", ipa: "/pʊt/" },
      { text: "could", ipa: "/kʊd/" },
    ],
    minimalPairs: [
      { left: "full", leftIpa: "/fʊl/", right: "fool", rightIpa: "/ful/" },
      { left: "pull", leftIpa: "/pʊl/", right: "pool", rightIpa: "/pul/" },
      { left: "could", leftIpa: "/kʊd/", right: "cooed", rightIpa: "/kud/" },
    ],
    sentences: ["Look at the good cookbook."],
    commonMistake: "Learners may pronounce /ʊ/ as long /u/.",
    correctionTip: "Keep it short, relaxed, and less rounded than /u/.",
    practiceDrill: "Repeat: book, good, put, could, look.",
    homework: "Practice /ʊ/ and /u/ pairs: full/fool, pull/pool.",
  },
  {
    id: "u",
    group: "vowels",
    ipa: "/u/",
    title: "/u/ as in blue",
    example: { text: "blue", ipa: "/blu/" },
    audioText: "oo. blue. Sue chose two blue shoes.",
    soundType: "High back tense rounded vowel",
    hint: "Round the lips more and hold the vowel a little longer.",
    mouthPosition: "Round the lips. Raise the back of the tongue high. Keep the vowel clear and tense.",
    spellings: ["oo: food", "u_e: rule", "ue: blue", "ew: new"],
    words: [
      { text: "blue", ipa: "/blu/" },
      { text: "food", ipa: "/fud/" },
      { text: "rule", ipa: "/rul/" },
      { text: "new", ipa: "/nu/" },
    ],
    minimalPairs: [
      { left: "fool", leftIpa: "/ful/", right: "full", rightIpa: "/fʊl/" },
      { left: "pool", leftIpa: "/pul/", right: "pull", rightIpa: "/pʊl/" },
      { left: "Luke", leftIpa: "/luk/", right: "look", rightIpa: "/lʊk/" },
    ],
    sentences: ["Sue chose two blue shoes."],
    commonMistake: "Learners may make /u/ too short or too central.",
    correctionTip: "Round the lips and keep the tongue high-back.",
    practiceDrill: "Repeat: blue, two, food, rule, new.",
    homework: "Read ten /u/ words and hold the vowel slightly longer than /ʊ/.",
  },
  {
    id: "cup",
    group: "vowels",
    ipa: "/ʌ/",
    title: "/ʌ/ as in cup",
    example: { text: "cup", ipa: "/kʌp/" },
    audioText: "uh. cup. My brother loves a sunny lunch.",
    soundType: "Mid central stressed vowel",
    hint: "Relax the jaw and tongue in the center of the mouth.",
    mouthPosition: "Open the mouth slightly. Keep the tongue central and relaxed. Lips are unrounded.",
    spellings: ["u: cup", "o: love", "ou: young", "oo: blood"],
    words: [
      { text: "cup", ipa: "/kʌp/" },
      { text: "love", ipa: "/lʌv/" },
      { text: "young", ipa: "/jʌŋ/" },
      { text: "blood", ipa: "/blʌd/" },
    ],
    minimalPairs: [
      { left: "cup", leftIpa: "/kʌp/", right: "cap", rightIpa: "/kæp/" },
      { left: "luck", leftIpa: "/lʌk/", right: "lock", rightIpa: "/lɑk/" },
      { left: "hut", leftIpa: "/hʌt/", right: "hot", rightIpa: "/hɑt/" },
    ],
    sentences: ["My brother loves a sunny lunch."],
    commonMistake: "Learners may use /ɑ/ or /æ/ instead of /ʌ/.",
    correctionTip: "Keep the vowel central, short, and relaxed.",
    practiceDrill: "Repeat: cup, love, young, lunch, brother.",
    homework: "Practice cup/cap and luck/lock minimal pairs.",
  },
  {
    id: "schwa",
    group: "vowels",
    ipa: "/ə/",
    title: "/ə/ as in about",
    example: { text: "about", ipa: "/əˈbaʊt/" },
    audioText: "schwa. about. I have a question about pronunciation.",
    soundType: "Unstressed central vowel",
    hint: "Very short, relaxed vowel in unstressed syllables.",
    mouthPosition: "Relax the tongue and jaw in a neutral position. Keep the vowel weak and short.",
    spellings: ["a: about", "e: problem", "o: lesson", "u: support"],
    words: [
      { text: "about", ipa: "/əˈbaʊt/" },
      { text: "teacher", ipa: "/ˈtitʃɚ/" },
      { text: "support", ipa: "/səˈpɔrt/" },
      { text: "problem", ipa: "/ˈprɑbləm/" },
    ],
    minimalPairs: [
      { left: "a bout", leftIpa: "/ə ˈbaʊt/", right: "about", rightIpa: "/əˈbaʊt/" },
      { left: "conduct noun", leftIpa: "/ˈkɑndəkt/", right: "conduct verb", rightIpa: "/kənˈdʌkt/" },
      { left: "present noun", leftIpa: "/ˈprɛzənt/", right: "present verb", rightIpa: "/prɪˈzɛnt/" },
    ],
    sentences: ["I have a question about pronunciation."],
    commonMistake: "Learners may pronounce every written vowel strongly.",
    correctionTip: "Reduce unstressed vowels to schwa when natural American rhythm requires it.",
    practiceDrill: "Repeat: about, support, problem, teacher.",
    homework: "Mark weak syllables in ten common words and reduce them.",
  },
  {
    id: "er-stressed",
    group: "vowels",
    ipa: "/ɝ/",
    title: "/ɝ/ as in bird",
    example: { text: "bird", ipa: "/bɝd/" },
    audioText: "er. bird. The first word was perfect.",
    soundType: "Stressed rhotic vowel",
    hint: "Hold a strong American r-colored vowel.",
    mouthPosition: "Pull the tongue back and raise the sides. Keep the center of the tongue tense without touching the roof.",
    spellings: ["ir: bird", "er: her", "ur: turn", "ear: learn"],
    words: [
      { text: "bird", ipa: "/bɝd/" },
      { text: "first", ipa: "/fɝst/" },
      { text: "learn", ipa: "/lɝn/" },
      { text: "turn", ipa: "/tɝn/" },
    ],
    minimalPairs: [
      { left: "bird", leftIpa: "/bɝd/", right: "bed", rightIpa: "/bɛd/" },
      { left: "fur", leftIpa: "/fɝ/", right: "far", rightIpa: "/fɑr/" },
      { left: "work", leftIpa: "/wɝk/", right: "walk", rightIpa: "/wɔk/" },
    ],
    sentences: ["The first word was perfect."],
    commonMistake: "Learners may drop the r-color or use a non-rhotic British-style vowel.",
    correctionTip: "Keep the American /r/ quality inside the vowel.",
    practiceDrill: "Repeat: bird, first, learn, turn, work.",
    homework: "Record ten stressed er/ir/ur words and keep the r-color strong.",
  },
  {
    id: "er-unstressed",
    group: "vowels",
    ipa: "/ɚ/",
    title: "/ɚ/ as in teacher",
    example: { text: "teacher", ipa: "/ˈtitʃɚ/" },
    audioText: "er. teacher. The teacher answered better.",
    soundType: "Unstressed rhotic vowel",
    hint: "A short weak vowel with American r-color.",
    mouthPosition: "Relax into schwa, then add light r-color by pulling the tongue back.",
    spellings: ["er: teacher", "or: doctor", "ar: dollar", "ure: picture"],
    words: [
      { text: "teacher", ipa: "/ˈtitʃɚ/" },
      { text: "doctor", ipa: "/ˈdɑktɚ/" },
      { text: "better", ipa: "/ˈbɛtɚ/" },
      { text: "picture", ipa: "/ˈpɪktʃɚ/" },
    ],
    minimalPairs: [
      { left: "teacher", leftIpa: "/ˈtitʃɚ/", right: "teach", rightIpa: "/titʃ/" },
      { left: "bigger", leftIpa: "/ˈbɪgɚ/", right: "big", rightIpa: "/bɪg/" },
      { left: "doctor", leftIpa: "/ˈdɑktɚ/", right: "dock", rightIpa: "/dɑk/" },
    ],
    sentences: ["The teacher answered better."],
    commonMistake: "Learners may drop final r in teacher or over-stress the ending.",
    correctionTip: "Keep it short, weak, and rhotic: teacher /ˈtitʃɚ/.",
    practiceDrill: "Repeat: teacher, doctor, better, picture.",
    homework: "Read ten -er final words and avoid adding a strong extra syllable.",
  },
  {
    id: "ai",
    group: "vowels",
    ipa: "/aɪ/",
    title: "/aɪ/ as in my",
    example: { text: "my", ipa: "/maɪ/" },
    audioText: "eye. my. I like my bright white bike.",
    soundType: "Low-to-high fronting diphthong",
    hint: "Start open /a/ and glide toward /ɪ/.",
    mouthPosition: "Open the jaw at the start, then raise the tongue and close the mouth slightly.",
    spellings: ["i: my", "y: sky", "igh: light", "ie: tie"],
    words: [
      { text: "my", ipa: "/maɪ/" },
      { text: "time", ipa: "/taɪm/" },
      { text: "light", ipa: "/laɪt/" },
      { text: "sky", ipa: "/skaɪ/" },
    ],
    minimalPairs: [
      { left: "my", leftIpa: "/maɪ/", right: "may", rightIpa: "/meɪ/" },
      { left: "light", leftIpa: "/laɪt/", right: "late", rightIpa: "/leɪt/" },
      { left: "bite", leftIpa: "/baɪt/", right: "bit", rightIpa: "/bɪt/" },
    ],
    sentences: ["I like my bright white bike."],
    commonMistake: "Learners may make /aɪ/ too short or forget the glide.",
    correctionTip: "Open at the start and finish with a clear upward movement.",
    practiceDrill: "Repeat: my, time, light, sky, bike.",
    homework: "Practice i_e, igh, and y spellings for /aɪ/.",
  },
  {
    id: "au",
    group: "vowels",
    ipa: "/aʊ/",
    title: "/aʊ/ as in now",
    example: { text: "now", ipa: "/naʊ/" },
    audioText: "ow. now. Now our house is downtown.",
    soundType: "Low-to-high back rounded diphthong",
    hint: "Start open and glide to rounded /ʊ/.",
    mouthPosition: "Begin with an open jaw, then round the lips as the vowel closes.",
    spellings: ["ow: now", "ou: house"],
    words: [
      { text: "now", ipa: "/naʊ/" },
      { text: "house", ipa: "/haʊs/" },
      { text: "around", ipa: "/əˈraʊnd/" },
      { text: "loud", ipa: "/laʊd/" },
    ],
    minimalPairs: [
      { left: "now", leftIpa: "/naʊ/", right: "no", rightIpa: "/noʊ/" },
      { left: "loud", leftIpa: "/laʊd/", right: "load", rightIpa: "/loʊd/" },
      { left: "house", leftIpa: "/haʊs/", right: "hose", rightIpa: "/hoʊz/" },
    ],
    sentences: ["Now our house is downtown."],
    commonMistake: "Learners may pronounce /aʊ/ like /oʊ/.",
    correctionTip: "Start more open before rounding: now, house, loud.",
    practiceDrill: "Repeat: now, house, around, loud, downtown.",
    homework: "Record ow/ou words and listen for the open start.",
  },
  {
    id: "oi",
    group: "vowels",
    ipa: "/ɔɪ/",
    title: "/ɔɪ/ as in boy",
    example: { text: "boy", ipa: "/bɔɪ/" },
    audioText: "oy. boy. The boy enjoyed the noisy toy.",
    soundType: "Back-to-front closing diphthong",
    hint: "Start rounded /ɔ/ and glide toward /ɪ/.",
    mouthPosition: "Begin with rounded lips, then relax and move the tongue forward and upward.",
    spellings: ["oy: boy", "oi: voice"],
    words: [
      { text: "boy", ipa: "/bɔɪ/" },
      { text: "voice", ipa: "/vɔɪs/" },
      { text: "choice", ipa: "/tʃɔɪs/" },
      { text: "enjoy", ipa: "/ɛnˈdʒɔɪ/" },
    ],
    minimalPairs: [
      { left: "boy", leftIpa: "/bɔɪ/", right: "bay", rightIpa: "/beɪ/" },
      { left: "voice", leftIpa: "/vɔɪs/", right: "vase", rightIpa: "/veɪs/" },
      { left: "toy", leftIpa: "/tɔɪ/", right: "toe", rightIpa: "/toʊ/" },
    ],
    sentences: ["The boy enjoyed the noisy toy."],
    commonMistake: "Learners may not glide enough from rounded to front.",
    correctionTip: "Start rounded, then move clearly toward /ɪ/.",
    practiceDrill: "Repeat: boy, voice, choice, enjoy, toy.",
    homework: "Practice oy and oi spelling groups in short sentences.",
  },
];

export const soundLessons = [...consonantLessons, ...vowelLessons];

export const courseModules: CourseModule[] = [
  {
    id: "syllables",
    number: "05",
    title: "Syllables",
    eyebrow: "Word building",
    description: "A syllable is a beat in a word. Clear syllable control helps learners pronounce long English words without rushing.",
    learn: [
      "Every syllable has a vowel sound, even when the spelling is confusing.",
      "English words can have one syllable, such as cat, or many syllables, such as pronunciation.",
      "Native rhythm depends on strong and weak syllables, not equal timing for every written letter.",
    ],
    examples: [
      { label: "1 syllable", text: "cat /kæt/, speak /spik/" },
      { label: "2 syllables", text: "teacher /ˈtitʃɚ/, happy /ˈhæpi/" },
      { label: "4 syllables", text: "pronunciation /prəˌnʌnsiˈeɪʃən/" },
    ],
    practice: [
      "Clap once for each vowel sound in a word.",
      "Mark the strongest syllable with a large circle.",
      "Read long words slowly, syllable by syllable, then connect them naturally.",
    ],
    quiz: [
      { question: "How many syllables are in teacher?", answer: "Two: teach-er /ˈtitʃɚ/." },
      { question: "What sound does every syllable need?", answer: "A vowel sound." },
    ],
  },
  {
    id: "word-stress",
    number: "06",
    title: "Word Stress",
    eyebrow: "Strong syllables",
    description: "Word stress tells listeners which syllable is strongest. It affects clarity more than many learners expect.",
    learn: [
      "A stressed syllable is longer, louder, and clearer.",
      "Unstressed syllables are shorter and often use schwa /ə/.",
      "Changing stress can change meaning, especially in noun-verb pairs.",
    ],
    examples: [
      { label: "First syllable", text: "TA-ble /ˈteɪbəl/, TEA-cher /ˈtitʃɚ/" },
      { label: "Second syllable", text: "a-BOUT /əˈbaʊt/, be-GIN /bɪˈgɪn/" },
      { label: "Meaning shift", text: "PRE-sent /ˈprɛzənt/ vs pre-SENT /prɪˈzɛnt/" },
    ],
    practice: [
      "Underline the stressed syllable in new vocabulary.",
      "Say the stressed syllable longer and clearer.",
      "Reduce the weak syllables instead of pronouncing every part equally.",
    ],
    quiz: [
      { question: "Which syllable is stressed in about?", answer: "The second syllable: a-BOUT /əˈbaʊt/." },
      { question: "What often happens to unstressed vowels?", answer: "They often reduce to schwa /ə/." },
    ],
  },
  {
    id: "sentence-stress",
    number: "07",
    title: "Sentence Stress",
    eyebrow: "Meaning in speech",
    description: "Sentence stress shows the important words. It makes English sound natural and easier to understand.",
    learn: [
      "Content words usually receive stress: nouns, main verbs, adjectives, adverbs, and negatives.",
      "Function words are usually weak: articles, prepositions, auxiliary verbs, and pronouns.",
      "The stressed word can change the meaning or contrast.",
    ],
    examples: [
      { label: "Neutral", text: "I NEED a NEW NOTEbook." },
      { label: "Contrast", text: "I need a new NOTEbook, not a new PHONE." },
      { label: "Correction", text: "SHE booked the class, not he." },
    ],
    practice: [
      "Circle the words that carry the main message.",
      "Read the sentence once slowly, then again with strong content words.",
      "Practice the same sentence with different stressed words.",
    ],
    quiz: [
      { question: "Which words usually carry stress?", answer: "Content words such as nouns, main verbs, adjectives, adverbs, and negatives." },
      { question: "Why does sentence stress matter?", answer: "It tells the listener what information is important." },
    ],
  },
  {
    id: "rhythm",
    number: "08",
    title: "Rhythm",
    eyebrow: "Strong and weak beats",
    description: "American English rhythm alternates strong beats and weak beats. This is why natural speech does not sound syllable-by-syllable.",
    learn: [
      "English is stress-timed: important beats are stronger, and weak syllables move quickly between them.",
      "Rhythm improves listening, speaking speed, and confidence.",
      "Weak forms help speech flow naturally.",
    ],
    examples: [
      { label: "Strong beats", text: "I WANT to SPEAK more CLEARly." },
      { label: "Weak form", text: "to often becomes /tə/ in natural speech." },
      { label: "Rhythm line", text: "DA da da DA da DA da" },
    ],
    practice: [
      "Tap the table on stressed words only.",
      "Say the weak words quickly and softly.",
      "Read short sentences with a steady beat.",
    ],
    quiz: [
      { question: "Is every English syllable equally strong?", answer: "No. English rhythm uses strong and weak syllables." },
      { question: "What happens to many function words?", answer: "They become weak and shorter in natural speech." },
    ],
  },
  {
    id: "intonation",
    number: "09",
    title: "Intonation",
    eyebrow: "Voice movement",
    description: "Intonation is the rise and fall of the voice. It helps show questions, certainty, contrast, emotion, and politeness.",
    learn: [
      "Falling intonation often sounds complete, certain, or final.",
      "Rising intonation often appears in yes/no questions or when checking information.",
      "Fall-rise intonation can show uncertainty, contrast, or polite correction.",
    ],
    examples: [
      { label: "Falling", text: "I finished the lesson. ↓" },
      { label: "Rising", text: "Did you finish the lesson? ↑" },
      { label: "Choice", text: "Do you want tea ↑ or coffee ↓?" },
    ],
    practice: [
      "Draw arrows over sentences before speaking.",
      "Practice yes/no questions with a gentle rise.",
      "Practice statements with a clean fall at the end.",
    ],
    quiz: [
      { question: "What intonation is common in yes/no questions?", answer: "A rising pattern." },
      { question: "What does falling intonation often show?", answer: "Completion, certainty, or finality." },
    ],
  },
  {
    id: "connected-speech",
    number: "10",
    title: "Connected Speech",
    eyebrow: "Natural linking",
    description: "Connected speech explains how words join in real American English. It improves both listening and speaking fluency.",
    learn: [
      "Final consonants often link to the next vowel.",
      "Some sounds blend or change when they meet.",
      "Weak forms and reductions make common phrases faster.",
    ],
    examples: [
      { label: "Linking", text: "turn off -> tur-noff" },
      { label: "Blending", text: "did you -> didja /ˈdɪdʒə/" },
      { label: "Reduction", text: "going to -> gonna /ˈgʌnə/ in casual speech" },
    ],
    practice: [
      "Underline final consonant + next vowel connections.",
      "Read word by word first, then link smoothly.",
      "Listen to a short clip and write the connected phrases you hear.",
    ],
    quiz: [
      { question: "What happens in turn off?", answer: "The final /n/ links to the next vowel: tur-noff." },
      { question: "Should formal speech use every casual reduction?", answer: "No. Learn reductions for listening, then choose what fits the situation." },
    ],
  },
  {
    id: "silent-letters",
    number: "11",
    title: "Silent Letters",
    eyebrow: "Spelling traps",
    description: "English spelling often includes letters that are not pronounced. Learners need sound patterns, not spelling guesses.",
    learn: [
      "Some letters are silent in common words because spelling preserves older forms.",
      "Silent letters can appear at the beginning, middle, or end of words.",
      "Pronunciation should be learned from sound and transcription, not spelling alone.",
    ],
    examples: [
      { label: "Silent k", text: "know /noʊ/, knife /naɪf/" },
      { label: "Silent b", text: "climb /klaɪm/, doubt /daʊt/" },
      { label: "Silent gh", text: "thought /θɔt/, though /ðoʊ/" },
    ],
    practice: [
      "Make a personal list of silent-letter words.",
      "Cross out silent letters and read only the pronounced sounds.",
      "Check IPA for new words that look confusing.",
    ],
    quiz: [
      { question: "Is the k pronounced in know?", answer: "No. know is /noʊ/." },
      { question: "Is gh always silent?", answer: "No. It can be silent, /f/ as in laugh, or part of other spelling patterns." },
    ],
  },
  {
    id: "spelling-to-sound-patterns",
    number: "12",
    title: "Spelling-to-Sound Patterns",
    eyebrow: "From letters to sounds",
    description: "This module helps learners connect common spellings with American English sounds without trusting spelling blindly.",
    learn: [
      "One letter can represent many sounds.",
      "One sound can have many spellings.",
      "Patterns are useful, but IPA and listening confirm the correct pronunciation.",
    ],
    examples: [
      { label: "Long a /eɪ/", text: "name, rain, day, eight" },
      { label: "Long e /i/", text: "see, speak, me, field" },
      { label: "th patterns", text: "think /θɪŋk/ vs this /ðɪs/" },
    ],
    practice: [
      "Group vocabulary by sound, not spelling.",
      "Write one IPA symbol beside each target word.",
      "Practice words with the same sound but different spelling.",
    ],
    quiz: [
      { question: "Can ea be pronounced more than one way?", answer: "Yes: speak /spik/, bread /brɛd/, great /greɪt/." },
      { question: "What confirms pronunciation when spelling is unclear?", answer: "Listening and IPA transcription." },
    ],
  },
  {
    id: "final-sounds",
    number: "13",
    title: "Final Sounds",
    eyebrow: "Clear endings",
    description: "Final consonants carry grammar and meaning. Clear endings help listeners understand tense, plurality, and word choice.",
    learn: [
      "Do not add an extra vowel after final consonants.",
      "Keep voiced endings voiced: bag /bæg/, not back /bæk/.",
      "Final consonant clusters can be practiced in slow steps.",
    ],
    examples: [
      { label: "No extra vowel", text: "cat /kæt/, not cat-uh" },
      { label: "Voicing contrast", text: "cap /kæp/ vs cab /kæb/" },
      { label: "Cluster", text: "asked /æskt/, texts /tɛksts/" },
    ],
    practice: [
      "Hold the final sound briefly without adding a vowel.",
      "Practice pairs such as cap/cab and back/bag.",
      "Build clusters one sound at a time: ask, asked.",
    ],
    quiz: [
      { question: "Why are final sounds important?", answer: "They can show grammar and distinguish words." },
      { question: "What common mistake should you avoid after final consonants?", answer: "Adding an extra vowel sound." },
    ],
  },
  {
    id: "s-endings",
    number: "14",
    title: "-s Endings",
    eyebrow: "Plural and third person",
    description: "The spelling -s has three common pronunciations: /s/, /z/, and /ɪz/.",
    learn: [
      "Use /s/ after voiceless sounds: cups /kʌps/.",
      "Use /z/ after voiced sounds and vowels: dogs /dɔgz/, plays /pleɪz/.",
      "Use /ɪz/ after sibilant sounds: classes /ˈklæsɪz/.",
    ],
    examples: [
      { label: "/s/", text: "cups, books, laughs" },
      { label: "/z/", text: "dogs, pens, days" },
      { label: "/ɪz/", text: "classes, watches, judges" },
    ],
    practice: [
      "Say the base word and identify the final sound.",
      "Choose /s/, /z/, or /ɪz/ before reading the word.",
      "Practice plural nouns and third-person verbs together.",
    ],
    quiz: [
      { question: "How is books pronounced?", answer: "/bʊks/ because /k/ is voiceless." },
      { question: "How is judges pronounced?", answer: "/ˈdʒʌdʒɪz/ because it ends in a sibilant sound." },
    ],
  },
  {
    id: "ed-endings",
    number: "15",
    title: "-ed Endings",
    eyebrow: "Past tense",
    description: "The spelling -ed has three common pronunciations: /t/, /d/, and /ɪd/.",
    learn: [
      "Use /t/ after voiceless sounds: worked /wɝkt/.",
      "Use /d/ after voiced sounds and vowels: played /pleɪd/.",
      "Use /ɪd/ after /t/ or /d/: wanted /ˈwɑntɪd/, needed /ˈnidɪd/.",
    ],
    examples: [
      { label: "/t/", text: "walked, watched, laughed" },
      { label: "/d/", text: "played, lived, called" },
      { label: "/ɪd/", text: "wanted, needed, decided" },
    ],
    practice: [
      "Say the base verb and identify the final sound.",
      "Add /t/, /d/, or /ɪd/ based on the sound, not the spelling.",
      "Read a past-tense paragraph and mark each ending.",
    ],
    quiz: [
      { question: "How is played pronounced?", answer: "/pleɪd/ because the base ends in a voiced vowel sound." },
      { question: "When do we use /ɪd/?", answer: "After base verbs ending in /t/ or /d/." },
    ],
  },
  {
    id: "common-mistakes",
    number: "16",
    title: "Common ESL Pronunciation Mistakes",
    eyebrow: "Problem solving",
    description: "This module collects high-impact pronunciation issues that many English learners need to notice and correct.",
    learn: [
      "Many mistakes come from using first-language sound categories for English sounds.",
      "Spelling can create incorrect pronunciation habits.",
      "Small sound contrasts can change meaning, grammar, and listener confidence.",
    ],
    examples: [
      { label: "Sound contrast", text: "/p/ vs /b/, /ɪ/ vs /i/, /θ/ vs /s/" },
      { label: "Final endings", text: "cap/cab, books/dogs/classes, walked/played/wanted" },
      { label: "Rhythm", text: "Pronouncing every syllable equally can sound unnatural." },
    ],
    practice: [
      "Choose three personal problem sounds.",
      "Practice minimal pairs daily for one week.",
      "Record the same text before and after practice.",
    ],
    quiz: [
      { question: "Why should you record yourself?", answer: "Recording helps you notice differences between your pronunciation and the target model." },
      { question: "What is a minimal pair?", answer: "Two words that differ by one sound, such as ship and sheep." },
    ],
  },
  {
    id: "practice-activities",
    number: "17",
    title: "Practice Activities",
    eyebrow: "Self-study routine",
    description: "Use these activities to turn the course from reading into real pronunciation improvement.",
    learn: [
      "Pronunciation improves through focused repetition, listening, and feedback.",
      "Short daily practice is more effective than rare long practice sessions.",
      "Recording and comparing builds awareness.",
    ],
    examples: [
      { label: "Minimal pair ladder", text: "ship, sheep, ship, sheep, sit, seat" },
      { label: "Shadowing", text: "Listen to one sentence and speak with the same rhythm and intonation." },
      { label: "Recording check", text: "Record, listen, mark one thing to improve, record again." },
    ],
    practice: [
      "Do five minutes of sound practice.",
      "Do five minutes of word and sentence practice.",
      "Do five minutes of recording and comparison.",
    ],
    quiz: [
      { question: "What is shadowing?", answer: "Listening and repeating with the same rhythm, stress, and intonation." },
      { question: "How long should daily practice be?", answer: "Even 10 to 15 focused minutes can help when done consistently." },
    ],
  },
  {
    id: "review-tests",
    number: "18",
    title: "Review Tests",
    eyebrow: "Check your progress",
    description: "Review tests help learners confirm that they can recognize sounds, choose endings, and apply stress patterns.",
    learn: [
      "A review test should check listening, pronunciation, and rules.",
      "Answer keys should be used after trying the task first.",
      "Mistakes show what to practice next.",
    ],
    examples: [
      { label: "IPA choice", text: "Choose the IPA symbol for the vowel in sit: /i/ or /ɪ/." },
      { label: "-s ending", text: "Choose the ending for dogs: /s/, /z/, or /ɪz/." },
      { label: "-ed ending", text: "Choose the ending for wanted: /t/, /d/, or /ɪd/." },
    ],
    practice: [
      "Take the sound chart review.",
      "Take the -s and -ed endings review.",
      "Record a one-minute pronunciation sample and evaluate final sounds.",
    ],
    quiz: [
      { question: "What is the vowel in sit?", answer: "/ɪ/." },
      { question: "What is the -s ending in dogs?", answer: "/z/." },
      { question: "What is the -ed ending in wanted?", answer: "/ɪd/." },
    ],
  },
  {
    id: "final-project",
    number: "19",
    title: "Final Pronunciation Project",
    eyebrow: "Put it together",
    description: "The final project turns the course into a complete pronunciation sample learners can compare and improve.",
    learn: [
      "Choose a short text that includes consonants, vowels, stress, rhythm, intonation, and connected speech.",
      "Prepare the text with IPA notes, stress marks, and intonation arrows.",
      "Record a first version, practice, then record a final version.",
    ],
    examples: [
      { label: "Project text", text: "My goal is to speak clearly, confidently, and naturally in American English." },
      { label: "Stress plan", text: "GOAL, SPEAK, CLEARly, CONfidently, NATurally, American ENglish" },
      { label: "Reflection", text: "Write three sounds you improved and three sounds to keep practicing." },
    ],
    practice: [
      "Select a 60- to 90-second text.",
      "Mark IPA for difficult words.",
      "Record version one, practice for three days, then record version two.",
      "Write a short self-study plan for the next month.",
    ],
    quiz: [
      { question: "What should the final project include?", answer: "A recorded speech sample, marked pronunciation notes, and a reflection." },
      { question: "What should you do after recording?", answer: "Compare, identify patterns, and create a next-step practice plan." },
    ],
  },
];

export const faqItems = [
  {
    question: "Is this English phonetics course free?",
    answer: "Yes. The course is free and open to study online.",
  },
  {
    question: "Do I need an account to study the course?",
    answer: "No. You do not need an account, login, payment, or enrollment.",
  },
  {
    question: "Is this course British or American English?",
    answer: "This course uses American English pronunciation and American rhotic IPA forms.",
  },
  {
    question: "Who is this course for?",
    answer: "It is for ESL learners who want clearer pronunciation, stronger listening, and more confident spoken English.",
  },
  {
    question: "Do I need to know IPA before starting?",
    answer: "No. IPA symbols are introduced with example words, audio support, and simple mouth-position notes.",
  },
  {
    question: "Can beginners use this course?",
    answer: "Yes. Beginners can start with the sound chart and simple sound lessons, then continue step by step.",
  },
  {
    question: "How should I practice pronunciation alone?",
    answer: "Listen, repeat, record yourself, compare with the model, and focus on one sound or pattern at a time.",
  },
  {
    question: "Can I book personal pronunciation feedback with Faris?",
    answer: "Yes. If you want personal correction and a study plan, you can contact Faris or book a pronunciation session.",
  },
] as const;
