import { text } from "./locale-copy";
import type { ReviewItem, TrackId } from "./types";

const reviewPath = (fileName: string) => `/images/landing/reviews/${fileName}`;

export const reviews: ReviewItem[] = [
  {
    id: "review-business-01",
    trackIds: ["business"],
    screenshot: reviewPath("review-business-01.png"),
    reviewer: "Madeline",
    country: "Belgium",
    date: "1 year ago",
    highlight: "Professional energy",
    transcription:
      "I'm very happy to have chosen Faris to learn English! He is friendly, patient and professional. He is a positive person, and it gives me energy to learn!",
    localizedExcerpt: text("Madeline highlights friendly, patient, professional teaching that gives her energy to learn.", {
      ar: "تؤكد ماديلين أن التدريب ودود وصبور واحترافي ويمنحها طاقة للتعلم.",
      tr: "Madeline, derslerin samimi, sabirli ve profesyonel oldugunu ve ona ogrenme enerjisi verdigini soyluyor.",
      es: "Madeline destaca una enseñanza amable, paciente y profesional que le da energia para aprender.",
      it: "Madeline sottolinea un insegnamento cordiale, paziente e professionale che le da energia per imparare.",
      de: "Madeline betont freundlichen, geduldigen und professionellen Unterricht, der ihr Energie zum Lernen gibt.",
      fr: "Madeline souligne un accompagnement patient, professionnel et motivant pour apprendre.",
      uk: "Madeline notes friendly, patient, professional teaching that gives her energy to learn.",
    }),
  },
  {
    id: "review-business-02",
    trackIds: ["business"],
    screenshot: reviewPath("review-business-02.png"),
    reviewer: "Paula Di Croce",
    country: "Brazil",
    date: "1 year ago",
    highlight: "Dedicated support",
    transcription:
      "Faris is an amazing person and an amazing teacher, he is dedicated to the students and to their needs. He also has a really good energy that makes the class really interesting!!",
    localizedExcerpt: text("Paula emphasizes dedication to student needs and a positive class energy.", {
      ar: "تشير باولا إلى اهتمام واضح باحتياجات الطلاب وطاقة إيجابية تجعل الدرس ممتعا.",
      tr: "Paula, ogrenci ihtiyaclarina adanmisligi ve derse enerji katan olumlu tonu vurguluyor.",
      es: "Paula destaca la dedicacion a las necesidades del estudiante y una energia positiva en clase.",
      it: "Paula evidenzia dedizione ai bisogni degli studenti e un'energia positiva in classe.",
      de: "Paula hebt die Ausrichtung auf die Bedurfnisse der Lernenden und eine positive Unterrichtsenergie hervor.",
      fr: "Paula souligne l'attention aux besoins des etudiants et une energie positive en cours.",
      uk: "Paula highlights dedication to student needs and positive class energy.",
    }),
  },
  {
    id: "review-business-03",
    trackIds: ["business"],
    screenshot: reviewPath("review-business-03.png"),
    reviewer: "Flavio",
    country: "Italy",
    date: "7 months ago",
    highlight: "Goal-focused help",
    transcription:
      "Faris is excellent and always very helpful. He quickly understands what you need and is truly dedicated to helping you reach your goals.",
    localizedExcerpt: text("Flavio says Faris quickly understands learner needs and stays dedicated to their goals.", {
      ar: "يقول فلافيو إن فارس يفهم احتياجات المتعلم بسرعة ويعمل بجد لمساعدته على تحقيق أهدافه.",
      tr: "Flavio, Faris'in ihtiyaci hizla anladigini ve hedeflere ulasmak icin ciddi destek verdigini soyluyor.",
      es: "Flavio afirma que Faris entiende rapido lo que el estudiante necesita y se dedica a sus metas.",
      it: "Flavio dice che Faris capisce rapidamente le esigenze dello studente ed e dedicato ai suoi obiettivi.",
      de: "Flavio sagt, dass Faris schnell versteht, was gebraucht wird, und engagiert auf Ziele hinarbeitet.",
      fr: "Flavio explique que Faris comprend vite les besoins et reste engage envers les objectifs.",
      uk: "Flavio says Faris quickly understands learner needs and stays dedicated to their goals.",
    }),
  },
  {
    id: "review-general-01",
    trackIds: ["business", "general"],
    screenshot: reviewPath("review-general-01.png"),
    reviewer: "Tamer",
    country: "Saudi Arabia",
    date: "2 months ago",
    highlight: "Structured correction",
    transcription:
      "Faris is highly professional and well-prepared. The lessons are structured, with clear objectives, and every session includes targeted corrections on pronunciation, grammar, and vocabulary. I especially appreciate the detailed feedback and the way mistakes are explained with practical examples, which makes improvement measurable from week to week.",
    localizedExcerpt: text("Tamer points to structured lessons, clear objectives, targeted correction, and measurable weekly progress.", {
      ar: "يشير تامر إلى دروس منظمة وأهداف واضحة وتصحيح موجه يجعل التطور قابلا للقياس أسبوعا بعد أسبوع.",
      tr: "Tamer; yapili dersleri, net hedefleri, hedefli duzeltmeleri ve haftalik olculebilir gelisimi vurguluyor.",
      es: "Tamer destaca clases estructuradas, objetivos claros, correcciones precisas y progreso medible cada semana.",
      it: "Tamer sottolinea lezioni strutturate, obiettivi chiari, correzioni mirate e progressi misurabili.",
      de: "Tamer betont strukturierte Stunden, klare Ziele, gezielte Korrektur und messbaren Fortschritt.",
      fr: "Tamer souligne des cours structures, des objectifs clairs, des corrections ciblees et des progres mesurables.",
      uk: "Tamer points to structured lessons, clear goals, targeted correction, and measurable progress.",
    }),
  },
  {
    id: "review-general-02",
    trackIds: ["general"],
    screenshot: reviewPath("review-general-02.png"),
    reviewer: "Sehad",
    country: "Austria",
    date: "3 years ago",
    highlight: "Friendly expertise",
    transcription:
      "I have never met such a friendly, knowledgeable, and professional Teacher as Mr. Faris. I have been working for a year with Mr. Faris, and I have learned a lot and enjoyed every lesson. If you want to be excellent in English and to have fun during your studies, you must take Mr. Faris as a teacher.",
    localizedExcerpt: text("Sehad describes a year of friendly, knowledgeable, professional lessons that he enjoyed.", {
      ar: "يصف سهاد عاما من الدروس الودية والمعرفية والاحترافية التي استمتع بها وتعلم منها كثيرا.",
      tr: "Sehad, bir yil boyunca samimi, bilgili ve profesyonel derslerden keyif aldigini soyluyor.",
      es: "Sehad describe un año de clases amables, profesionales y enriquecedoras.",
      it: "Sehad descrive un anno di lezioni piacevoli, competenti e professionali.",
      de: "Sehad beschreibt ein Jahr freundlichen, kompetenten und professionellen Unterrichts.",
      fr: "Sehad decrit une annee de cours agreables, professionnels et riches en apprentissage.",
      uk: "Sehad describes a year of friendly, knowledgeable, professional lessons he enjoyed.",
    }),
  },
  {
    id: "review-general-03",
    trackIds: ["general"],
    screenshot: reviewPath("review-general-03.png"),
    reviewer: "Beatriz",
    country: "Spain",
    date: "4 years ago",
    highlight: "Fluency growth",
    transcription:
      "I am very happy with the classes I have received, I certainly learn and improve with each lesson, expanding my vocabulary and my fluency speaking in a short time. Faris has adapted very well to my level of English creating stress-free, lively and active conversations that make classes very dynamic where time passes quickly. After each class he sends you a pdf with all the notes. He is very polite and committed, I recommend him.",
    localizedExcerpt: text("Beatriz reports vocabulary and fluency growth through lively, stress-free, level-adapted lessons.", {
      ar: "تذكر بياتريس تطورا في المفردات والطلاقة من خلال دروس نشطة ومريحة ومناسبة لمستواها.",
      tr: "Beatriz, seviyesine uygun, stressiz ve canli derslerle kelime ve akicilik gelisimi yasadigini belirtiyor.",
      es: "Beatriz habla de mas vocabulario y fluidez gracias a clases dinamicas, sin estres y adaptadas a su nivel.",
      it: "Beatriz nota crescita nel vocabolario e nella fluidita grazie a lezioni vive, serene e adatte al suo livello.",
      de: "Beatriz beschreibt mehr Wortschatz und Sprechfluss durch lebendige, stressfreie und passende Stunden.",
      fr: "Beatriz mentionne plus de vocabulaire et de fluidite grace a des cours vivants et adaptes.",
      uk: "Beatriz reports vocabulary and fluency growth through lively, stress-free lessons.",
    }),
  },
  {
    id: "review-speaking-confidence-01",
    trackIds: ["general"],
    screenshot: reviewPath("review-speaking-confidence-01.png"),
    reviewer: "Mohammed",
    country: "Saudi Arabia",
    date: "7 months ago",
    highlight: "Speaking confidence",
    transcription:
      "Faris is an amazing teacher! He explains everything clearly and makes each lesson enjoyable. I've already noticed big improvements in my English speaking and confidence. I always look forward to our classes and highly recommend him to anyone who wants to improve their English.",
    localizedExcerpt: text("Mohammed noticed major improvements in speaking and confidence through clear, enjoyable lessons.", {
      ar: "لاحظ محمد تطورا كبيرا في التحدث والثقة بفضل الشرح الواضح والدروس الممتعة.",
      tr: "Mohammed, net ve keyifli derslerle konusma ve ozguveninde buyuk gelisme fark ettigini soyluyor.",
      es: "Mohammed noto grandes mejoras en su speaking y confianza con clases claras y agradables.",
      it: "Mohammed ha notato grandi miglioramenti nel parlato e nella sicurezza grazie a lezioni chiare e piacevoli.",
      de: "Mohammed bemerkte starke Verbesserungen im Sprechen und Selbstvertrauen durch klare, angenehme Stunden.",
      fr: "Mohammed a observe de grands progres en expression orale et en confiance grace a des cours clairs.",
      uk: "Mohammed noticed major improvements in speaking and confidence through clear lessons.",
    }),
  },
  {
    id: "review-ielts-01",
    trackIds: ["ielts"],
    screenshot: reviewPath("review-ielts-01.png"),
    reviewer: "Emmanuel",
    country: "France",
    date: "11 months ago",
    highlight: "IELTS 7.5",
    transcription:
      "Faris is a very good teacher. He knows exactly how to push you in the right direction and each session is efficient and focused. I scored a 7.5 on the IELTS thanks to his support.",
    localizedExcerpt: text("Emmanuel credits efficient, focused IELTS support with helping him score 7.5.", {
      ar: "ينسب إيمانويل حصوله على 7.5 في الآيلتس إلى دعم فعال ومركز.",
      tr: "Emmanuel, 7.5 IELTS sonucunu verimli ve odakli destege bagliyor.",
      es: "Emmanuel atribuye su 7.5 en IELTS a un apoyo eficiente y enfocado.",
      it: "Emmanuel collega il suo 7.5 IELTS a un supporto efficiente e mirato.",
      de: "Emmanuel fuhrt seine IELTS 7.5 auf effiziente und fokussierte Unterstutzung zuruck.",
      fr: "Emmanuel attribue son 7.5 a l'IELTS a un accompagnement efficace et cible.",
      uk: "Emmanuel credits efficient, focused IELTS support with helping him score 7.5.",
    }),
  },
  {
    id: "review-ielts-02",
    trackIds: ["ielts"],
    screenshot: reviewPath("review-ielts-02.png"),
    reviewer: "Omar",
    country: "Saudi Arabia",
    date: "7 months ago",
    highlight: "IELTS Academic 7.5",
    transcription:
      "Mr Faris is an amazing teacher. He helped me to achieve a band score 7.5 in the IELTS academic test. I enjoyed my lessons with him, and he didn't only prepare me academically and linguistically but also mentally by motivating and encouraging me. He also taught me self-learning skills, which enhanced my performance. He had a great role, after God, in achieving this.",
    localizedExcerpt: text("Omar says IELTS preparation combined academic, language, mental, and self-learning support.", {
      ar: "يقول عمر إن التحضير للآيلتس جمع بين الدعم الأكاديمي واللغوي والنفسي ومهارات التعلم الذاتي.",
      tr: "Omar, IELTS hazirliginin akademik, dilsel, zihinsel ve oz-ogrenme destegi sundugunu belirtiyor.",
      es: "Omar destaca apoyo academico, linguistico, mental y de autoaprendizaje para IELTS.",
      it: "Omar evidenzia supporto accademico, linguistico, mentale e di autoapprendimento per IELTS.",
      de: "Omar nennt akademische, sprachliche, mentale und selbstlernende Unterstutzung fur IELTS.",
      fr: "Omar souligne un soutien academique, linguistique, mental et d'autonomie pour l'IELTS.",
      uk: "Omar says IELTS preparation combined academic, language, mental, and self-learning support.",
    }),
  },
  {
    id: "review-ielts-03",
    trackIds: ["ielts"],
    screenshot: reviewPath("review-ielts-03.png"),
    reviewer: "Alia",
    country: "Kuwait",
    date: "3 weeks ago",
    highlight: "IELTS Band 7",
    transcription:
      "Yesterday, I received my IELTS result (overall band 7). Thank you, Teacher Faris, for all the support and advice you gave me. I wish you all the best and continued success.",
    localizedExcerpt: text("Alia reports an overall IELTS Band 7 and thanks Faris for support and advice.", {
      ar: "تذكر علياء حصولها على Band 7 في الآيلتس وتشكر فارس على الدعم والنصائح.",
      tr: "Alia, IELTS overall Band 7 aldigini ve destek ile tavsiyeler icin tesekkur ettigini soyluyor.",
      es: "Alia informa un Band 7 general en IELTS y agradece el apoyo y los consejos.",
      it: "Alia comunica un Band 7 IELTS complessivo e ringrazia per supporto e consigli.",
      de: "Alia berichtet von IELTS Overall Band 7 und dankt fur Unterstutzung und Rat.",
      fr: "Alia annonce un Band 7 global a l'IELTS et remercie Faris pour le soutien et les conseils.",
      uk: "Alia reports an overall IELTS Band 7 and thanks Faris for support and advice.",
    }),
  },
  {
    id: "review-teacher-training-01",
    trackIds: ["teacher-training"],
    screenshot: reviewPath("review-teacher-training-01.jpg"),
    reviewer: "Teacher training participant",
    date: "Recent",
    highlight: "Practical teacher training",
    transcription:
      "I attended Mr. Faris Rashad's teacher training sessions, and they were extremely practical and valuable. The training helped me improve how I teach speaking, vocabulary using CECDW, grammar in connection with students' real lives, and how to give effective feedback. I also learned useful techniques such as Think-Pair-Share, Bloom's Taxonomy, the i+1 rule, reading and listening for gist and details, classroom management, and ways to improve students' vocabulary range. The sessions also included helpful soft skills, Zoom techniques, and AI tips to create a better learning experience. Overall, the training was professional, clear, and highly beneficial for teachers who want to improve their teaching practice.",
    localizedExcerpt: text("The participant describes practical teacher training on speaking, vocabulary, grammar, feedback, classroom management, Zoom, and AI tools.", {
      ar: "تصف المشاركة تدريبا عمليا للمعلمين في التحدث والمفردات والقواعد والتغذية الراجعة وإدارة الصف وتقنيات زووم والذكاء الاصطناعي.",
      tr: "Katilimci; konusma, kelime, gramer, geri bildirim, sinif yonetimi, Zoom ve AI konularinda pratik egitim aldigini belirtiyor.",
      es: "La participante describe formacion practica sobre speaking, vocabulario, gramatica, feedback, gestion de clase, Zoom e IA.",
      it: "La partecipante descrive formazione pratica su speaking, vocabolario, grammatica, feedback, gestione classe, Zoom e IA.",
      de: "Die Teilnehmerin beschreibt praxisnahe Fortbildung zu Speaking, Wortschatz, Grammatik, Feedback, Klassenfuhrung, Zoom und KI.",
      fr: "La participante decrit une formation pratique sur oral, vocabulaire, grammaire, feedback, gestion de classe, Zoom et IA.",
      uk: "The participant describes practical teacher training on speaking, vocabulary, grammar, feedback, classroom management, Zoom, and AI.",
    }),
  },
];

export function getReviewsForTrack(trackId: TrackId) {
  return reviews.filter((review) => review.trackIds.includes(trackId));
}
