import { text } from "@/content/locale-copy";

export const placementCopy = {
  eyebrow: text("CEFR-aligned English placement test", {
    ar: "اختبار تحديد مستوى انجليزي متوافق مع CEFR",
    tr: "CEFR uyumlu Ingilizce seviye testi",
    es: "Prueba de nivel de ingles alineada con CEFR",
    it: "Test di livello inglese allineato al CEFR",
    de: "CEFR-orientierter Englisch-Einstufungstest",
    fr: "Test de niveau d'anglais aligne CECR",
    uk: "Тест рівня англійської за CEFR",
  }),
  title: text("15-minute English level check", {
    ar: "اختبار مستوى انجليزي في 15 دقيقة",
    tr: "15 dakikalik Ingilizce seviye kontrolu",
    es: "Revision de nivel de ingles en 15 minutos",
    it: "Controllo del livello di inglese in 15 minuti",
    de: "15-Minuten Englisch-Levelcheck",
    fr: "Bilan de niveau d'anglais en 15 minutes",
    uk: "15-хвилинна перевірка рівня англійської",
  }),
  description: text(
    "Check grammar and vocabulary with a serious adaptive diagnostic, then receive a clear A1-C2 CEFR estimate and a personalised next-step recommendation.",
    {
      ar: "اختبر المفردات والقواعد والقراءة من خلال تشخيص قصير متكيف، ثم احصل على تقدير واضح لمستواك حسب CEFR وتوصية للخطوة التالية.",
      tr: "Kisa uyarlanabilir bir tanilama ile kelime, gramer ve okumayi kontrol edin; ardindan CEFR tahmini ve kisisel sonraki adim onerisi alin.",
      es: "Evalua vocabulario, gramatica y lectura con un diagnostico adaptativo breve y recibe una estimacion CEFR y una recomendacion personalizada.",
      it: "Controlla vocabolario, grammatica e lettura con una diagnosi adattiva breve e ricevi una stima CEFR e un consiglio personalizzato.",
      de: "Prufe Wortschatz, Grammatik und Lesen mit einem kurzen adaptiven Check und erhalte eine CEFR-Einschatzung mit Empfehlung.",
      fr: "Evaluez vocabulaire, grammaire et lecture avec un court diagnostic adaptatif et recevez une estimation CECR et une recommandation.",
      uk: "Перевірте словник, граматику й читання в короткому адаптивному тесті та отримайте оцінку CEFR і рекомендацію.",
    },
  ),
  descriptionCurrent: text(
    "Check grammar and vocabulary with a serious adaptive diagnostic, then receive a clear A1-C2 CEFR estimate and a personalised next-step recommendation.",
    {
      ar: "اختبر القواعد والمفردات من خلال تشخيص متكيف جاد، ثم احصل على تقدير واضح لمستواك من A1 إلى C2 حسب CEFR وتوصية شخصية للخطوة التالية.",
      tr: "Ciddi ve uyarlanabilir bir tani ile gramer ve kelime bilginizi kontrol edin; A1-C2 CEFR tahmini ve kisisel sonraki adim onerisi alin.",
      es: "Evalua gramatica y vocabulario con un diagnostico adaptativo serio y recibe una estimacion CEFR A1-C2 con una recomendacion personalizada.",
      it: "Valuta grammatica e vocabolario con una diagnosi adattiva seria e ricevi una stima CEFR A1-C2 con un consiglio personalizzato.",
      de: "Prufe Grammatik und Wortschatz mit einem serioesen adaptiven Check und erhalte eine A1-C2 CEFR-Einschaetzung mit Empfehlung.",
      fr: "Evaluez grammaire et vocabulaire avec un diagnostic adaptatif serieux et recevez une estimation CECR A1-C2 avec une recommandation personnalisee.",
      uk: "Перевірте граматику й словниковий запас у серйозному адаптивному тесті та отримайте оцінку CEFR A1-C2 з персональною рекомендацією.",
    },
  ),
  scopeNoteCurrent: text(
    "This is a placement estimate based on grammar and vocabulary, not an official certificate. Speaking, listening, writing, and real-time communication are best confirmed in a live diagnostic lesson.",
    {
      ar: "هذا تقدير لتحديد المستوى مبني على القواعد والمفردات وليس شهادة رسمية. من الأفضل تأكيد التحدث والاستماع والكتابة والتواصل المباشر في حصة تشخيصية مباشرة.",
      tr: "Bu resmi bir sertifika degil; gramer ve kelimeye dayali bir seviye tahminidir. Konusma, dinleme, yazma ve anlik iletisim canli derste dogrulanir.",
      es: "Es una estimacion basada en gramatica y vocabulario, no un certificado oficial. Speaking, listening, writing y comunicacion real se confirman mejor en una clase diagnostica.",
      it: "E una stima basata su grammatica e vocabolario, non un certificato ufficiale. Speaking, listening, writing e comunicazione reale vanno confermati in una lezione diagnostica.",
      de: "Dies ist eine Einstufung auf Basis von Grammatik und Wortschatz, kein offizielles Zertifikat. Sprechen, Hoeren, Schreiben und Echtzeitkommunikation sollten live geprueft werden.",
      fr: "C'est une estimation basee sur la grammaire et le vocabulaire, pas un certificat officiel. L'oral, l'ecoute, l'ecrit et la communication en temps reel se confirment en cours diagnostique.",
      uk: "Це оцінка рівня на основі граматики й словникового запасу, а не офіційний сертифікат. Говоріння, аудіювання, письмо й живу комунікацію краще підтвердити на уроці.",
    },
  ),
  introDescriptionCurrent: text(
    "You will answer an adaptive set of English questions drawn from a large A1-C2 item library. The test checks vocabulary depth and grammar control without pretending to measure every skill.",
    {
      ar: "ستجيب عن مجموعة متكيفة من أسئلة الإنجليزية من مكتبة كبيرة تغطي A1 إلى C2. يقيس الاختبار عمق المفردات والتحكم في القواعد من دون الادعاء بأنه يقيس كل المهارات.",
      tr: "A1-C2 araligindaki buyuk bir soru kutuphanesinden uyarlanabilir Ingilizce sorulari cevaplayacaksiniz. Test kelime derinligi ve gramer kontrolunu olcer; her beceriyi olctugunu iddia etmez.",
      es: "Responderas preguntas adaptativas de una gran biblioteca A1-C2. El test mide profundidad de vocabulario y control gramatical sin presentarse como medicion completa de todas las destrezas.",
      it: "Risponderai a domande adattive tratte da una grande banca A1-C2. Il test misura profondita lessicale e controllo grammaticale senza fingere di misurare ogni abilita.",
      de: "Du beantwortest adaptive Englischfragen aus einer grossen A1-C2-Fragenbank. Der Test prueft Wortschatztiefe und Grammatik, ohne alle Fertigkeiten messen zu wollen.",
      fr: "Vous repondrez a des questions adaptatives issues d'une grande banque A1-C2. Le test evalue la richesse lexicale et le controle grammatical sans pretendre mesurer toutes les competences.",
      uk: "Ви відповідатимете на адаптивні запитання з великої бази A1-C2. Тест перевіряє словниковий запас і граматику, але не претендує на вимір усіх навичок.",
    },
  ),
  start: text("Start the test", {
    ar: "ابدأ الاختبار",
    tr: "Teste basla",
    es: "Empezar la prueba",
    it: "Inizia il test",
    de: "Test starten",
    fr: "Commencer le test",
    uk: "Почати тест",
  }),
  beginDiagnostic: text("Begin diagnostic", {
    ar: "ابدأ التشخيص",
    tr: "Taniya basla",
    es: "Iniciar diagnostico",
    it: "Inizia diagnosi",
    de: "Diagnose starten",
    fr: "Lancer le diagnostic",
    uk: "Почати діагностику",
  }),
  beginNow: text("Begin diagnostic now", {
    ar: "ابدأ التشخيص الآن",
    tr: "Taniya simdi basla",
    es: "Iniciar diagnostico ahora",
    it: "Inizia diagnosi ora",
    de: "Diagnose jetzt starten",
    fr: "Lancer le diagnostic maintenant",
    uk: "Почати діагностику зараз",
  }),
  estimatedTime: text("Estimated time: around 15 minutes", {
    ar: "الوقت المتوقع: حوالي 15 دقيقة",
    tr: "Tahmini sure: yaklasik 15 dakika",
    es: "Tiempo estimado: unos 15 minutos",
    it: "Tempo stimato: circa 15 minuti",
    de: "Geschatzte Zeit: etwa 15 Minuten",
    fr: "Temps estime : environ 15 minutes",
    uk: "Орієнтовний час: близько 15 хвилин",
  }),
  scopeNote: text(
    "This is a placement estimate based on grammar and vocabulary, not an official certificate. Speaking, listening, writing, and real-time communication are best confirmed in a live diagnostic lesson.",
    {
      ar: "هذا تقدير لتحديد المستوى وليس شهادة رسمية. من الأفضل تأكيد التحدث والاستماع والكتابة في حصة تشخيصية مباشرة.",
      tr: "Bu resmi bir sertifika degil, seviye tahminidir. Konusma, dinleme ve yazma en iyi canli tanilama dersinde dogrulanir.",
      es: "Es una estimacion de nivel, no un certificado oficial. Speaking, listening y writing se confirman mejor en una clase diagnostica.",
      it: "E una stima di livello, non un certificato ufficiale. Speaking, listening e writing vanno confermati in una lezione diagnostica.",
      de: "Dies ist eine Einstufung, kein offizielles Zertifikat. Sprechen, Horen und Schreiben sollten live gepruft werden.",
      fr: "C'est une estimation de placement, pas un certificat officiel. L'oral, l'ecoute et l'ecrit se confirment en cours diagnostique.",
      uk: "Це орієнтовна оцінка рівня, не офіційний сертифікат. Говоріння, аудіювання й письмо краще підтвердити на уроці.",
    },
  ),
  measurements: {
    title: text("What it measures", {
      ar: "ما الذي يقيسه الاختبار",
      tr: "Testin olctugu alanlar",
      es: "Que mide",
      it: "Che cosa misura",
      de: "Was der Test misst",
      fr: "Ce que le test mesure",
      uk: "Що перевіряє тест",
    }),
    vocabulary: text("Vocabulary depth and chunks", {
      ar: "عمق المفردات والتعبيرات الجاهزة",
      tr: "Kelime derinligi ve kalip ifadeler",
      es: "Profundidad de vocabulario y frases utiles",
      it: "Profondita lessicale e blocchi di lingua",
      de: "Wortschatztiefe und Sprachbausteine",
      fr: "Richesse du vocabulaire et groupes de mots",
      uk: "Глибина словника та сталі фрази",
    }),
    grammar: text("Grammar form and meaning", {
      ar: "القواعد من حيث الشكل والمعنى",
      tr: "Dil bilgisi bicimi ve anlami",
      es: "Forma y significado gramatical",
      it: "Forma e significato grammaticale",
      de: "Grammatikform und Bedeutung",
      fr: "Forme grammaticale et sens",
      uk: "Граматична форма і значення",
    }),
    reading: text("Reading gist, detail, and inference", {
      ar: "فهم الفكرة العامة والتفاصيل والاستنتاج",
      tr: "Okumada ana fikir, detay ve cikarim",
      es: "Idea general, detalle e inferencia en lectura",
      it: "Idea generale, dettaglio e inferenza nella lettura",
      de: "Lesen: Hauptaussage, Detail und Schlussfolgerung",
      fr: "Lecture : idee generale, detail et inference",
      uk: "Читання: головна думка, деталі та висновки",
    }),
  },
  diagnosticSection: {
    eyebrow: text("Adaptive diagnostic", {
      ar: "تشخيص متكيف",
      tr: "Uyarlanabilir tani",
      es: "Diagnostico adaptativo",
      it: "Diagnosi adattiva",
      de: "Adaptiver Check",
      fr: "Diagnostic adaptatif",
      uk: "Адаптивна діагностика",
    }),
    title: text("Find the level evidence before choosing a study path", {
      ar: "اكتشف دليل مستواك قبل اختيار مسار الدراسة",
      tr: "Calisma yolunu secmeden once seviye kanitini gorun",
      es: "Encuentra evidencia de nivel antes de elegir tu ruta",
      it: "Trova prove del livello prima di scegliere il percorso",
      de: "Finde Niveauhinweise, bevor du den Lernweg waehlst",
      fr: "Reperez les indices de niveau avant de choisir un parcours",
      uk: "Побачте докази рівня перед вибором навчального шляху",
    }),
    description: text("Answer a short adaptive sequence, then enter your details to view a useful placement summary and recommendation.", {
      ar: "أجب عن مجموعة قصيرة متكيفة، ثم أدخل بياناتك لعرض ملخص تحديد المستوى والتوصية المناسبة.",
      tr: "Kisa bir uyarlanabilir diziyi cevaplayin, sonra seviye ozetinizi ve oneriyi gormek icin bilgilerinizi girin.",
      es: "Responde una secuencia adaptativa breve y luego introduce tus datos para ver un resumen y una recomendacion.",
      it: "Rispondi a una breve sequenza adattiva, poi inserisci i dati per vedere riepilogo e consiglio.",
      de: "Beantworte eine kurze adaptive Reihe und gib dann deine Daten ein, um Zusammenfassung und Empfehlung zu sehen.",
      fr: "Repondez a une courte sequence adaptative, puis entrez vos informations pour voir le bilan et la recommandation.",
      uk: "Дайте відповіді на коротку адаптивну серію, потім введіть дані, щоб побачити підсумок і рекомендацію.",
    }),
  },
  introTitle: text("A focused diagnostic before you choose your next step", {
    ar: "تشخيص مركز قبل اختيار خطوتك التالية",
    tr: "Sonraki adimdan once odakli bir tani",
    es: "Un diagnostico claro antes de elegir el siguiente paso",
    it: "Una diagnosi mirata prima del passo successivo",
    de: "Ein fokussierter Check vor dem naechsten Schritt",
    fr: "Un diagnostic cible avant de choisir la suite",
    uk: "Сфокусована діагностика перед наступним кроком",
  }),
  introDescription: text("You will answer an adaptive set of English questions drawn from a large A1-C2 item library. The test checks vocabulary depth and grammar control without pretending to measure every skill.", {
    ar: "ستجيب عن مجموعة قصيرة ومتكيفة من أسئلة اللغة الإنجليزية. يقيس الاختبار عمق المفردات والتحكم في القواعد وفهم القراءة، من دون الادعاء بأنه يقيس كل المهارات.",
    tr: "Kisa ve uyarlanabilir bir Ingilizce soru seti cevaplayacaksiniz. Test kelime derinligi, gramer kontrolu ve okuma anlamayi olcer; her beceriyi olctugunu iddia etmez.",
    es: "Responderas un conjunto breve y adaptativo de preguntas en ingles. El test mide vocabulario, control gramatical y comprension lectora sin presentarse como una medicion completa de todas las destrezas.",
    it: "Risponderai a una breve serie adattiva di domande in inglese. Il test controlla lessico, accuratezza grammaticale e comprensione della lettura senza fingere di misurare ogni abilita.",
    de: "Du beantwortest kurze adaptive Englischfragen. Der Test prueft Wortschatz, Grammatik und Leseverstehen, ohne alle Fertigkeiten messen zu wollen.",
    fr: "Vous repondrez a une courte serie adaptative de questions en anglais. Le test evalue vocabulaire, grammaire et comprehension ecrite sans pretendre mesurer toutes les competences.",
    uk: "Ви відповісте на короткий адаптивний набір англійських запитань. Тест перевіряє словник, граматику й читання, але не претендує на вимір усіх навичок.",
  }),
  introCards: {
    vocabulary: text("Meaning, chunks, collocations, and lexical choice.", {
      ar: "المعنى والتعبيرات الجاهزة والمتلازمات والاختيار المعجمي.",
      tr: "Anlam, kaliplar, esdizimler ve kelime secimi.",
      es: "Significado, frases, colocaciones y eleccion lexica.",
      it: "Significato, blocchi, collocazioni e scelta lessicale.",
      de: "Bedeutung, Sprachbausteine, Kollokationen und Wortwahl.",
      fr: "Sens, groupes de mots, collocations et choix lexical.",
      uk: "Значення, сталі фрази, сполучуваність і вибір слів.",
    }),
    grammar: text("Form and meaning in useful sentence contexts.", {
      ar: "الشكل والمعنى داخل جمل مفيدة وسياقية.",
      tr: "Yararli cumle baglamlarinda bicim ve anlam.",
      es: "Forma y significado en contextos utiles.",
      it: "Forma e significato in frasi utili.",
      de: "Form und Bedeutung in nuetzlichen Satzkontexten.",
      fr: "Forme et sens dans des phrases utiles.",
      uk: "Форма й значення в корисних реченнях.",
    }),
    reading: text("Gist, detail, inference, and language in context.", {
      ar: "الفكرة العامة والتفاصيل والاستنتاج واللغة في السياق.",
      tr: "Ana fikir, detay, cikarim ve baglamda dil.",
      es: "Idea general, detalle, inferencia y lengua en contexto.",
      it: "Idea generale, dettaglio, inferenza e lingua nel contesto.",
      de: "Hauptaussage, Detail, Schlussfolgerung und Sprache im Kontext.",
      fr: "Idee generale, detail, inference et langue en contexte.",
      uk: "Головна думка, деталі, висновки й мова в контексті.",
    }),
  },
  goalPlaceholder: text("Example: IELTS Band 7, better meetings, general speaking confidence...", {
    ar: "مثال: IELTS Band 7، اجتماعات أفضل، ثقة أكبر في المحادثة...",
    tr: "Ornek: IELTS 7, daha iyi toplantilar, genel konusma guveni...",
    es: "Ejemplo: IELTS 7, mejores reuniones, mas confianza al hablar...",
    it: "Esempio: IELTS 7, riunioni migliori, piu sicurezza nel parlato...",
    de: "Beispiel: IELTS 7, bessere Meetings, mehr Sicherheit beim Sprechen...",
    fr: "Exemple : IELTS 7, meilleures reunions, plus d'assurance a l'oral...",
    uk: "Приклад: IELTS 7, кращі зустрічі, більше впевненості в мовленні...",
  }),
  currentGoal: text("What is your main English goal?", {
    ar: "ما هدفك الأساسي في الإنجليزية؟",
    tr: "Ana Ingilizce hedefiniz nedir?",
    es: "Cual es tu objetivo principal en ingles?",
    it: "Qual e il tuo obiettivo principale in inglese?",
    de: "Was ist dein Hauptziel in Englisch?",
    fr: "Quel est votre objectif principal en anglais ?",
    uk: "Яка ваша головна мета в англійській?",
  }),
  selfEstimate: text("Current level, if you know it", {
    ar: "مستواك الحالي إذا كنت تعرفه",
    tr: "Biliyorsaniz mevcut seviyeniz",
    es: "Nivel actual, si lo conoces",
    it: "Livello attuale, se lo conosci",
    de: "Aktuelles Niveau, falls bekannt",
    fr: "Niveau actuel, si vous le connaissez",
    uk: "Поточний рівень, якщо знаєте",
  }),
  interestedTrack: text("Interested track", {
    ar: "المسار المناسب لك",
    tr: "Ilgilendiginiz program",
    es: "Programa de interes",
    it: "Percorso di interesse",
    de: "Interessierter Kursbereich",
    fr: "Parcours qui vous interesse",
    uk: "Цікавий напрям",
  }),
  selectOption: text("Select an option", {
    ar: "اختر خيارا",
    tr: "Bir secenek secin",
    es: "Selecciona una opcion",
    it: "Seleziona un'opzione",
    de: "Option auswahlen",
    fr: "Selectionnez une option",
    uk: "Виберіть варіант",
  }),
  progress: text("Progress", {
    ar: "التقدم",
    tr: "Ilerleme",
    es: "Progreso",
    it: "Avanzamento",
    de: "Fortschritt",
    fr: "Progression",
    uk: "Прогрес",
  }),
  next: text("Next", {
    ar: "التالي",
    tr: "Sonraki",
    es: "Siguiente",
    it: "Avanti",
    de: "Weiter",
    fr: "Suivant",
    uk: "Далі",
  }),
  finishStage: text("Continue", {
    ar: "متابعة",
    tr: "Devam et",
    es: "Continuar",
    it: "Continua",
    de: "Fortfahren",
    fr: "Continuer",
    uk: "Продовжити",
  }),
  detailsTitle: text("Enter your details to view your placement result", {
    ar: "أدخل بياناتك لعرض نتيجة تحديد المستوى",
    tr: "Seviye sonucunu gormek icin bilgilerinizi girin",
    es: "Introduce tus datos para ver tu resultado",
    it: "Inserisci i tuoi dati per vedere il risultato",
    de: "Gib deine Daten ein, um dein Ergebnis zu sehen",
    fr: "Entrez vos informations pour voir votre resultat",
    uk: "Введіть дані, щоб побачити результат",
  }),
  detailsDescription: text(
    "Enter your details to view your placement result and receive a personalised next-step recommendation.",
    {
      ar: "أدخل بياناتك لعرض نتيجتك والحصول على توصية شخصية للخطوة التالية.",
      tr: "Sonucunuzu gormek ve kisisel sonraki adim onerisi almak icin bilgilerinizi girin.",
      es: "Introduce tus datos para ver tu resultado y recibir una recomendacion personalizada.",
      it: "Inserisci i tuoi dati per vedere il risultato e ricevere un consiglio personalizzato.",
      de: "Gib deine Daten ein, um dein Ergebnis und eine personliche Empfehlung zu erhalten.",
      fr: "Entrez vos informations pour voir votre resultat et recevoir une recommandation personnalisee.",
      uk: "Введіть дані, щоб побачити результат і отримати персональну рекомендацію.",
    },
  ),
  fields: {
    fullName: text("Full name", {
      ar: "الاسم الكامل",
      tr: "Ad soyad",
      es: "Nombre completo",
      it: "Nome completo",
      de: "Vollstaendiger Name",
      fr: "Nom complet",
      uk: "Повне ім'я",
    }),
    age: text("Age", {
      ar: "العمر",
      tr: "Yas",
      es: "Edad",
      it: "Eta",
      de: "Alter",
      fr: "Age",
      uk: "Вік",
    }),
    nationality: text("Nationality", {
      ar: "الجنسية",
      tr: "Uyruk",
      es: "Nacionalidad",
      it: "Nazionalita",
      de: "Nationalitaet",
      fr: "Nationalite",
      uk: "Національність",
    }),
    whatsapp: text("WhatsApp phone", {
      ar: "رقم واتساب",
      tr: "WhatsApp telefonu",
      es: "Telefono de WhatsApp",
      it: "Telefono WhatsApp",
      de: "WhatsApp-Nummer",
      fr: "Telephone WhatsApp",
      uk: "Телефон WhatsApp",
    }),
    telegram: text("Telegram username or phone", {
      ar: "اسم مستخدم تيليجرام أو الهاتف",
      tr: "Telegram kullanici adi veya telefon",
      es: "Usuario o telefono de Telegram",
      it: "Username o telefono Telegram",
      de: "Telegram-Benutzername oder Telefon",
      fr: "Identifiant ou telephone Telegram",
      uk: "Telegram username або телефон",
    }),
    email: text("Email", {
      ar: "البريد الإلكتروني",
      tr: "E-posta",
      es: "Email",
      it: "Email",
      de: "E-Mail",
      fr: "Email",
      uk: "Email",
    }),
    preferredLanguage: text("Preferred language", {
      ar: "اللغة المفضلة",
      tr: "Tercih edilen dil",
      es: "Idioma preferido",
      it: "Lingua preferita",
      de: "Bevorzugte Sprache",
      fr: "Langue preferee",
      uk: "Бажана мова",
    }),
    learningGoal: text("Learning goal", {
      ar: "هدف التعلم",
      tr: "Ogrenme hedefi",
      es: "Objetivo de aprendizaje",
      it: "Obiettivo di apprendimento",
      de: "Lernziel",
      fr: "Objectif d'apprentissage",
      uk: "Навчальна мета",
    }),
    consent: text("I consent to being contacted about my placement result.", {
      ar: "أوافق على التواصل معي بخصوص نتيجة تحديد المستوى.",
      tr: "Seviye sonucum hakkinda benimle iletisime gecilmesine izin veriyorum.",
      es: "Acepto que se me contacte sobre mi resultado de nivel.",
      it: "Acconsento a essere contattato sul mio risultato.",
      de: "Ich stimme zu, wegen meines Einstufungsergebnisses kontaktiert zu werden.",
      fr: "J'accepte d'etre contacte au sujet de mon resultat.",
      uk: "Я погоджуюся, щоб зі мною зв'язалися щодо результату.",
    }),
  },
  detailsReady: text("Your diagnostic is ready", {
    ar: "تشخيصك جاهز",
    tr: "Taniniz hazir",
    es: "Tu diagnostico esta listo",
    it: "La tua diagnosi e pronta",
    de: "Dein Ergebnis ist bereit",
    fr: "Votre diagnostic est pret",
    uk: "Ваша діагностика готова",
  }),
  noPaywallMessage: text("Your result is not blocked by payment. These details help Faris understand who took the test and prepare the right recommendation.", {
    ar: "نتيجتك ليست محجوبة بالدفع. هذه البيانات تساعد فارس على معرفة من أجرى الاختبار وتحضير التوصية المناسبة.",
    tr: "Sonucunuz odeme ile kilitli degil. Bu bilgiler Faris'in testi kimin aldigini anlamasina ve dogru oneriyi hazirlamasina yardim eder.",
    es: "Tu resultado no esta bloqueado por pago. Estos datos ayudan a Faris a entender quien hizo el test y preparar la recomendacion adecuada.",
    it: "Il risultato non e bloccato da un pagamento. Questi dati aiutano Faris a capire chi ha fatto il test e preparare il consiglio giusto.",
    de: "Dein Ergebnis ist nicht hinter einer Zahlung gesperrt. Diese Angaben helfen Faris, den Test einzuordnen und die passende Empfehlung vorzubereiten.",
    fr: "Votre resultat n'est pas bloque par un paiement. Ces informations aident Faris a comprendre votre profil et a preparer la bonne recommandation.",
    uk: "Результат не заблокований оплатою. Ці дані допомагають Фарісу зрозуміти, хто пройшов тест, і підготувати правильну рекомендацію.",
  }),
  submitDetails: text("View my result", {
    ar: "عرض نتيجتي",
    tr: "Sonucumu goster",
    es: "Ver mi resultado",
    it: "Mostra il mio risultato",
    de: "Mein Ergebnis anzeigen",
    fr: "Voir mon resultat",
    uk: "Показати мій результат",
  }),
  saving: text("Saving your diagnostic...", {
    ar: "جار حفظ التشخيص...",
    tr: "Tanilamaniz kaydediliyor...",
    es: "Guardando tu diagnostico...",
    it: "Salvataggio della diagnosi...",
    de: "Diagnose wird gespeichert...",
    fr: "Enregistrement du diagnostic...",
    uk: "Зберігаємо діагностику...",
  }),
  resultTitle: text("Your English placement result", {
    ar: "نتيجة تحديد مستوى الإنجليزية",
    tr: "Ingilizce seviye sonucunuz",
    es: "Tu resultado de nivel de ingles",
    it: "Il tuo risultato di livello inglese",
    de: "Dein Englisch-Einstufungsergebnis",
    fr: "Votre resultat de niveau d'anglais",
    uk: "Ваш результат рівня англійської",
  }),
  resultMissing: text("No saved placement result was found in this browser.", {
    ar: "لم يتم العثور على نتيجة محفوظة في هذا المتصفح.",
    tr: "Bu tarayicida kayitli sonuc bulunamadi.",
    es: "No se encontro ningun resultado guardado en este navegador.",
    it: "Nessun risultato salvato trovato in questo browser.",
    de: "In diesem Browser wurde kein gespeichertes Ergebnis gefunden.",
    fr: "Aucun resultat enregistre n'a ete trouve dans ce navigateur.",
    uk: "У цьому браузері не знайдено збереженого результату.",
  }),
  resultHeroDescription: text("Use your result as a starting point, then confirm speaking, listening, and writing in a live diagnostic lesson.", {
    ar: "استخدم نتيجتك كنقطة بداية، ثم أكد التحدث والاستماع والكتابة في حصة تشخيصية مباشرة.",
    tr: "Sonucunuzu baslangic noktasi olarak kullanin; konusma, dinleme ve yazmayi canli tani dersinde dogrulayin.",
    es: "Usa tu resultado como punto de partida y confirma speaking, listening y writing en una clase diagnostica en vivo.",
    it: "Usa il risultato come punto di partenza e conferma speaking, listening e writing in una lezione diagnostica dal vivo.",
    de: "Nutze dein Ergebnis als Ausgangspunkt und bestaetige Sprechen, Hoeren und Schreiben in einer Live-Diagnosestunde.",
    fr: "Utilisez votre resultat comme point de depart, puis confirmez oral, ecoute et ecrit en cours diagnostique.",
    uk: "Використайте результат як стартову точку, а говоріння, аудіювання й письмо підтвердьте на живому діагностичному уроці.",
  }),
  retakeTest: text("Retake the test", {
    ar: "إعادة الاختبار",
    tr: "Testi tekrar al",
    es: "Repetir la prueba",
    it: "Rifai il test",
    de: "Test wiederholen",
    fr: "Refaire le test",
    uk: "Пройти тест ще раз",
  }),
  overallLevel: text("Estimated CEFR level", {
    ar: "المستوى التقديري حسب CEFR",
    tr: "Tahmini CEFR seviyesi",
    es: "Nivel CEFR estimado",
    it: "Livello CEFR stimato",
    de: "Geschaetztes CEFR-Niveau",
    fr: "Niveau CECR estime",
    uk: "Орієнтовний рівень CEFR",
  }),
  confidence: text("Confidence", {
    ar: "درجة الثقة",
    tr: "Guven",
    es: "Confianza",
    it: "Affidabilita",
    de: "Sicherheit",
    fr: "Fiabilite",
    uk: "Впевненість",
  }),
  subskills: text("Subskill breakdown", {
    ar: "تفصيل المهارات",
    tr: "Alt beceri dagilimi",
    es: "Desglose por destrezas",
    it: "Dettaglio delle abilita",
    de: "Teilfertigkeiten",
    fr: "Detail par competence",
    uk: "Розподіл за навичками",
  }),
  strengths: text("Strengths noticed", {
    ar: "نقاط القوة الملحوظة",
    tr: "Gorulen guclu yanlar",
    es: "Fortalezas observadas",
    it: "Punti di forza osservati",
    de: "Erkannte Staerken",
    fr: "Points forts observes",
    uk: "Помічені сильні сторони",
  }),
  gaps: text("Likely gaps noticed", {
    ar: "الفجوات المحتملة",
    tr: "Olasi eksikler",
    es: "Posibles brechas",
    it: "Possibili lacune",
    de: "Wahrscheinliche Luecken",
    fr: "Lacunes probables",
    uk: "Ймовірні прогалини",
  }),
  recommendations: text("Best-practice recommendations", {
    ar: "توصيات عملية فعالة",
    tr: "En iyi uygulama onerileri",
    es: "Recomendaciones de buenas practicas",
    it: "Raccomandazioni efficaci",
    de: "Empfehlungen fuer gutes Lernen",
    fr: "Recommandations efficaces",
    uk: "Практичні рекомендації",
  }),
  firstLessons: text("Recommended first lessons", {
    ar: "الحصص الأولى المقترحة",
    tr: "Onerilen ilk dersler",
    es: "Primeras clases recomendadas",
    it: "Prime lezioni consigliate",
    de: "Empfohlene erste Stunden",
    fr: "Premiers cours recommandes",
    uk: "Рекомендовані перші уроки",
  }),
  teachingPriorities: text("Teaching priorities", {
    ar: "أولويات التدريس",
    tr: "Ogretim oncelikleri",
    es: "Prioridades de aprendizaje",
    it: "Priorita didattiche",
    de: "Lernprioritaeten",
    fr: "Priorites de travail",
    uk: "Навчальні пріоритети",
  }),
  recommendedProgram: text("Recommended program", {
    ar: "البرنامج المقترح",
    tr: "Onerilen program",
    es: "Programa recomendado",
    it: "Programma consigliato",
    de: "Empfohlenes Programm",
    fr: "Programme recommande",
    uk: "Рекомендована програма",
  }),
  bookDiagnostic: text("Book a diagnostic lesson on Preply", {
    ar: "احجز حصة تشخيصية على Preply",
    tr: "Preply'de tani dersi ayirt",
    es: "Reserva una clase diagnostica en Preply",
    it: "Prenota una lezione diagnostica su Preply",
    de: "Diagnosestunde auf Preply buchen",
    fr: "Reserver un cours diagnostique sur Preply",
    uk: "Забронювати діагностичний урок на Preply",
  }),
  contactCta: text("Register interest", {
    ar: "سجل اهتمامك",
    tr: "Ilgini kaydet",
    es: "Registrar interes",
    it: "Registra interesse",
    de: "Interesse anmelden",
    fr: "Signaler votre interet",
    uk: "Залишити заявку",
  }),
  retrySave: text("Retry saving result", {
    ar: "إعادة محاولة حفظ النتيجة",
    tr: "Sonucu kaydetmeyi tekrar dene",
    es: "Reintentar guardar el resultado",
    it: "Riprova a salvare il risultato",
    de: "Speichern erneut versuchen",
    fr: "Reessayer l'enregistrement",
    uk: "Спробувати зберегти ще раз",
  }),
  savedSuccess: text("Your result was saved successfully.", {
    ar: "تم حفظ نتيجتك بنجاح.",
    tr: "Sonucunuz basariyla kaydedildi.",
    es: "Tu resultado se guardo correctamente.",
    it: "Il risultato e stato salvato correttamente.",
    de: "Dein Ergebnis wurde erfolgreich gespeichert.",
    fr: "Votre resultat a bien ete enregistre.",
    uk: "Ваш результат успішно збережено.",
  }),
  storageWarning: text(
    "Your result is visible here, but saving it to the lead sheet did not work. You can retry from this page.",
    {
      ar: "نتيجتك ظاهرة هنا، لكن حفظها في جدول العملاء لم ينجح. يمكنك إعادة المحاولة من هذه الصفحة.",
      tr: "Sonucunuz burada gorunuyor, ancak lead sayfasina kayit calismadi. Bu sayfadan tekrar deneyebilirsiniz.",
      es: "Tu resultado aparece aqui, pero no se pudo guardar en la hoja de leads. Puedes reintentarlo desde esta pagina.",
      it: "Il risultato e visibile qui, ma il salvataggio nel foglio lead non e riuscito. Puoi riprovare da questa pagina.",
      de: "Dein Ergebnis ist hier sichtbar, aber das Speichern in der Lead-Tabelle hat nicht funktioniert. Du kannst es hier erneut versuchen.",
      fr: "Votre resultat est visible ici, mais l'enregistrement dans la feuille de leads n'a pas fonctionne. Vous pouvez reessayer ici.",
      uk: "Результат видно тут, але збереження в таблицю лідів не спрацювало. Можна повторити спробу на цій сторінці.",
    },
  ),
  questionLanguageNote: text("Questions remain in English because this diagnostic measures English directly.", {
    ar: "تبقى الأسئلة باللغة الإنجليزية لأن هذا التشخيص يقيس الإنجليزية مباشرة.",
    tr: "Sorular Ingilizce kalir cunku bu tani Ingilizceyi dogrudan olcer.",
    es: "Las preguntas permanecen en ingles porque este diagnostico mide ingles directamente.",
    it: "Le domande restano in inglese perche questa diagnosi misura direttamente l'inglese.",
    de: "Die Fragen bleiben auf Englisch, weil dieser Check Englisch direkt misst.",
    fr: "Les questions restent en anglais, car ce diagnostic mesure directement l'anglais.",
    uk: "Запитання залишаються англійською, бо тест безпосередньо вимірює англійську.",
  }),
  resultPhrases: {
    likely: text("Likely", {
      ar: "غالبا",
      tr: "Muhtemelen",
      es: "Probable",
      it: "Probabile",
      de: "Wahrscheinlich",
      fr: "Probablement",
      uk: "Ймовірно",
    }),
    strong: text("Strong", {
      ar: "قوي",
      tr: "Güçlü",
      es: "Solido",
      it: "Solido",
      de: "Stark",
      fr: "Solide",
      uk: "Сильний",
    }),
    borderline: text("borderline", {
      ar: "قريب من الحد بين المستويين",
      tr: "sinirda",
      es: "en frontera",
      it: "al confine",
      de: "an der Grenze",
      fr: "a la limite",
      uk: "на межі",
    }),
    upperB2: text("Upper-B2 / approaching C1", {
      ar: "B2 مرتفع / قريب من C1",
      tr: "Ust B2 / C1'e yaklasiyor",
      es: "B2 alto / acercandose a C1",
      it: "B2 alto / verso C1",
      de: "Oberes B2 / naehert sich C1",
      fr: "B2 avance / proche de C1",
      uk: "Верхній B2 / наближається до C1",
    }),
    currentEnglishLooks: text("Your current English looks", {
      ar: "يبدو مستواك الحالي في الإنجليزية",
      tr: "Mevcut Ingilizceniz su duzeyde gorunuyor",
      es: "Tu ingles actual parece estar",
      it: "Il tuo inglese attuale sembra",
      de: "Dein aktuelles Englisch wirkt",
      fr: "Votre anglais actuel semble",
      uk: "Ваша поточна англійська виглядає як",
    }),
    with: text("with", {
      ar: "مع",
      tr: "ve",
      es: "con",
      it: "con",
      de: "mit",
      fr: "avec",
      uk: "з",
    }),
    strongerThan: text("stronger than", {
      ar: "أقوى من",
      tr: "sundan daha guclu",
      es: "mas fuerte que",
      it: "piu forte di",
      de: "staerker als",
      fr: "plus solide que",
      uk: "сильніше, ніж",
    }),
    personalTraining: text("Personalised English training", {
      ar: "تدريب إنجليزي مخصص",
      tr: "Kisisellestirilmis Ingilizce egitimi",
      es: "Entrenamiento de ingles personalizado",
      it: "Formazione di inglese personalizzata",
      de: "Personalisiertes Englischtraining",
      fr: "Formation d'anglais personnalisee",
      uk: "Персоналізоване навчання англійської",
    }),
    strongestSentence: text("is the strongest area in this short diagnostic.", {
      ar: "هي أقوى منطقة في هذا التشخيص القصير.",
      tr: "bu kisa tanidaki en guclu alandir.",
      es: "es el area mas fuerte en este diagnostico breve.",
      it: "e l'area piu forte in questa breve diagnosi.",
      de: "ist der staerkste Bereich in diesem kurzen Check.",
      fr: "est le domaine le plus solide dans ce court diagnostic.",
      uk: "є найсильнішою зоною в цій короткій діагностиці.",
    }),
    solidEvidence: text("You handled a good share of level-targeted items successfully.", {
      ar: "تعاملت بنجاح مع نسبة جيدة من الأسئلة الموجهة للمستوى.",
      tr: "Seviye odakli sorularin iyi bir kismini basariyla yaptiniz.",
      es: "Resolviste bien una buena parte de los items de nivel.",
      it: "Hai gestito bene una buona parte degli item mirati al livello.",
      de: "Du hast einen guten Teil der niveaugezielten Aufgaben erfolgreich geloest.",
      fr: "Vous avez reussi une bonne partie des items cibles par niveau.",
      uk: "Ви успішно виконали добру частину завдань свого рівня.",
    }),
    enoughEvidence: text("You showed enough evidence to identify a practical starting band.", {
      ar: "قدمت دليلا كافيا لتحديد نطاق بداية عملي.",
      tr: "Pratik bir baslangic bandi belirlemek icin yeterli kanit gosterdiniz.",
      es: "Mostraste evidencia suficiente para identificar una banda inicial practica.",
      it: "Hai mostrato prove sufficienti per identificare una fascia di partenza pratica.",
      de: "Du hast genug Hinweise fuer einen praktischen Startbereich gezeigt.",
      fr: "Vous avez donne assez d'indices pour definir une zone de depart utile.",
      uk: "Ви дали достатньо доказів для практичного стартового рівня.",
    }),
    weakestSentence: text("needs the most careful follow-up.", {
      ar: "تحتاج إلى المتابعة الأكثر دقة.",
      tr: "en dikkatli takip gerektiren alandir.",
      es: "necesita el seguimiento mas cuidadoso.",
      it: "richiede il seguito piu attento.",
      de: "braucht die sorgfaeltigste Nacharbeit.",
      fr: "demande le suivi le plus attentif.",
      uk: "потребує найуважнішого подальшого опрацювання.",
    }),
    boundaryLive: text("Your result sits near a CEFR boundary, so live confirmation will be especially useful.", {
      ar: "نتيجتك قريبة من حد بين مستويين في CEFR، لذلك سيكون التأكيد المباشر مفيدا جدا.",
      tr: "Sonucunuz bir CEFR sinirina yakin; bu yuzden canli dogrulama ozellikle faydali olur.",
      es: "Tu resultado esta cerca de una frontera CEFR, asi que la confirmacion en vivo sera especialmente util.",
      it: "Il risultato e vicino a un confine CEFR, quindi la conferma dal vivo sara particolarmente utile.",
      de: "Dein Ergebnis liegt nahe an einer CEFR-Grenze; eine Live-Bestaetigung ist daher besonders nuetzlich.",
      fr: "Votre resultat est proche d'une limite CECR ; une confirmation en direct sera donc tres utile.",
      uk: "Ваш результат близький до межі CEFR, тому живе підтвердження буде особливо корисним.",
    }),
    liveSkills: text("Speaking, listening, and writing may show a different level and should be checked live.", {
      ar: "قد يظهر التحدث والاستماع والكتابة مستوى مختلفا ويجب فحصها مباشرة.",
      tr: "Konusma, dinleme ve yazma farkli bir seviye gosterebilir ve canli kontrol edilmelidir.",
      es: "Speaking, listening y writing pueden mostrar otro nivel y conviene revisarlos en vivo.",
      it: "Speaking, listening e writing possono mostrare un livello diverso e vanno controllati dal vivo.",
      de: "Sprechen, Hoeren und Schreiben koennen anders ausfallen und sollten live geprueft werden.",
      fr: "L'oral, l'ecoute et l'ecrit peuvent differer et doivent etre verifies en direct.",
      uk: "Говоріння, аудіювання й письмо можуть мати інший рівень і мають перевірятися наживо.",
    }),
    summaryBalanced: text("Your profile is balanced across the tested skills.", {
      ar: "ملفك متوازن بين المهارات التي تم اختبارها.",
      tr: "Profiliniz test edilen beceriler arasinda dengeli.",
      es: "Tu perfil esta equilibrado entre las destrezas evaluadas.",
      it: "Il tuo profilo e equilibrato tra le abilita testate.",
      de: "Dein Profil ist in den getesteten Fertigkeiten ausgeglichen.",
      fr: "Votre profil est equilibre dans les competences testees.",
      uk: "Ваш профіль збалансований у перевірених навичках.",
    }),
    recommendedTrack: text("Recommended track", {
      ar: "المسار المقترح",
      tr: "Onerilen yol",
      es: "Ruta recomendada",
      it: "Percorso consigliato",
      de: "Empfohlener Weg",
      fr: "Parcours recommande",
      uk: "Рекомендований напрям",
    }),
  },
  trackNextSteps: {
    ielts: text("Book an IELTS diagnostic lesson to connect this level estimate to your target band.", {
      ar: "احجز حصة تشخيصية لـ IELTS لربط هذا التقدير بدرجتك المستهدفة.",
      tr: "Bu seviye tahminini hedef bandinizla baglamak icin IELTS tani dersi ayirtin.",
      es: "Reserva una clase diagnostica de IELTS para conectar esta estimacion con tu banda objetivo.",
      it: "Prenota una lezione diagnostica IELTS per collegare questa stima al band obiettivo.",
      de: "Buche eine IELTS-Diagnosestunde, um diese Einschaetzung mit deinem Zielband zu verbinden.",
      fr: "Reservez un cours diagnostique IELTS pour relier cette estimation a votre score cible.",
      uk: "Забронюйте діагностичний урок IELTS, щоб пов'язати цей рівень із цільовим балом.",
    }),
    business: text("Book a Business English diagnostic lesson to turn your result into meeting, interview, and presentation practice.", {
      ar: "احجز حصة تشخيصية في إنجليزية الأعمال لتحويل نتيجتك إلى تدريب على الاجتماعات والمقابلات والعروض.",
      tr: "Sonucunuzu toplanti, mulakat ve sunum calismasina cevirmek icin Business English tani dersi ayirtin.",
      es: "Reserva una clase diagnostica de Business English para convertir tu resultado en practica de reuniones, entrevistas y presentaciones.",
      it: "Prenota una diagnosi di Business English per trasformare il risultato in pratica per riunioni, colloqui e presentazioni.",
      de: "Buche eine Business-English-Diagnosestunde fuer Meeting-, Interview- und Praesentationspraxis.",
      fr: "Reservez un cours diagnostique Business English pour transformer le resultat en pratique de reunions, entretiens et presentations.",
      uk: "Забронюйте діагностичний урок Business English для практики зустрічей, співбесід і презентацій.",
    }),
    "teacher-training": text("Book an advanced diagnostic lesson to check precision, methodology goals, or teacher-development needs.", {
      ar: "احجز حصة تشخيصية متقدمة لفحص الدقة أو أهداف المنهجية أو احتياجات تطوير المعلمين.",
      tr: "Hassasiyet, metodoloji hedefleri veya ogretmen gelisimi ihtiyaclarini kontrol etmek icin ileri tani dersi ayirtin.",
      es: "Reserva una clase diagnostica avanzada para revisar precision, metodologia o desarrollo docente.",
      it: "Prenota una diagnosi avanzata per verificare precisione, metodologia o sviluppo docente.",
      de: "Buche eine fortgeschrittene Diagnosestunde fuer Praezision, Methodikziele oder Lehrerentwicklung.",
      fr: "Reservez un cours diagnostique avance pour verifier precision, methodologie ou developpement enseignant.",
      uk: "Забронюйте просунутий діагностичний урок для точності, методики або розвитку викладача.",
    }),
    general: text("Book a General English diagnostic lesson to confirm speaking, listening, and writing and build a study plan.", {
      ar: "احجز حصة تشخيصية في الإنجليزية العامة لتأكيد التحدث والاستماع والكتابة وبناء خطة دراسة.",
      tr: "Konusma, dinleme ve yazmayi dogrulamak ve plan yapmak icin General English tani dersi ayirtin.",
      es: "Reserva una clase diagnostica de General English para confirmar speaking, listening y writing y crear un plan.",
      it: "Prenota una diagnosi di General English per confermare speaking, listening e writing e creare un piano.",
      de: "Buche eine General-English-Diagnosestunde, um Sprechen, Hoeren und Schreiben zu bestaetigen und einen Plan zu bauen.",
      fr: "Reservez un cours diagnostique General English pour confirmer oral, ecoute et ecrit et creer un plan.",
      uk: "Забронюйте діагностичний урок General English, щоб підтвердити говоріння, аудіювання й письмо та скласти план.",
    }),
  },
  recommendationItems: {
    spacedReview: text("Use spaced review and retrieval practice instead of rereading notes passively.", {
      ar: "استخدم المراجعة المتباعدة واستدعاء المعلومات بدلا من إعادة قراءة الملاحظات بشكل سلبي.",
      tr: "Notlari pasif okumak yerine aralikli tekrar ve hatirlama alistirmasi kullanin.",
      es: "Usa repaso espaciado y practica de recuperacion en lugar de releer apuntes pasivamente.",
      it: "Usa ripasso dilazionato e pratica di recupero invece di rileggere appunti passivamente.",
      de: "Nutze verteiltes Wiederholen und Abrufuebung statt passivem Notizenlesen.",
      fr: "Utilisez la revision espacee et la recuperation active au lieu de relire passivement.",
      uk: "Використовуйте інтервальне повторення й активне пригадування замість пасивного перечитування.",
    }),
    errorLog: text("Keep a small error log and revisit corrected sentences until they become automatic.", {
      ar: "احتفظ بسجل أخطاء صغير وراجع الجمل المصححة حتى تصبح تلقائية.",
      tr: "Kucuk bir hata gunlugu tutun ve duzeltilmis cumleleri otomatik olana kadar tekrar edin.",
      es: "Mantén un pequeño registro de errores y repasa frases corregidas hasta automatizarlas.",
      it: "Tieni un piccolo registro degli errori e rivedi le frasi corrette finche diventano automatiche.",
      de: "Fuehre ein kleines Fehlerprotokoll und wiederhole korrigierte Saetze, bis sie automatisch werden.",
      fr: "Tenez un petit journal d'erreurs et retravaillez les phrases corrigees jusqu'a automatisation.",
      uk: "Ведіть невеликий журнал помилок і повторюйте виправлені речення до автоматизму.",
    }),
    chunks: text("Learn vocabulary in chunks, collocations, and short useful sentences.", {
      ar: "تعلم المفردات في تعبيرات جاهزة ومتلازمات وجمل قصيرة مفيدة.",
      tr: "Kelimeyi kaliplar, esdizimler ve kisa yararli cumlelerle ogrenin.",
      es: "Aprende vocabulario en frases, colocaciones y oraciones cortas utiles.",
      it: "Impara il lessico in blocchi, collocazioni e brevi frasi utili.",
      de: "Lerne Wortschatz in Sprachbausteinen, Kollokationen und kurzen nuetzlichen Saetzen.",
      fr: "Apprenez le vocabulaire en groupes de mots, collocations et phrases utiles.",
      uk: "Вивчайте словник через сталі фрази, сполучуваність і короткі корисні речення.",
    }),
    grammar: text("Train grammar through communication tasks, then correct repeated patterns.", {
      ar: "درّب القواعد من خلال مهام تواصلية، ثم صحح الأنماط المتكررة.",
      tr: "Dil bilgisini iletisim gorevleriyle calisin, sonra tekrar eden kaliplari duzeltin.",
      es: "Entrena la gramatica con tareas comunicativas y corrige patrones repetidos.",
      it: "Allena la grammatica con compiti comunicativi, poi correggi gli schemi ricorrenti.",
      de: "Trainiere Grammatik in Kommunikationsaufgaben und korrigiere wiederkehrende Muster.",
      fr: "Travaillez la grammaire par des taches communicatives, puis corrigez les schemas recurrents.",
      uk: "Тренуйте граматику через комунікативні завдання, потім виправляйте повторювані шаблони.",
    }),
    reading: text("Read level-appropriate texts repeatedly and practise gist, detail, and inference questions.", {
      ar: "اقرأ نصوصا مناسبة للمستوى بشكل متكرر وتدرب على الفكرة العامة والتفاصيل والاستنتاج.",
      tr: "Seviyeye uygun metinleri tekrarli okuyun; ana fikir, detay ve cikarim sorulari calisin.",
      es: "Lee textos adecuados a tu nivel varias veces y practica idea general, detalle e inferencia.",
      it: "Leggi testi adatti al livello piu volte e pratica idea generale, dettagli e inferenze.",
      de: "Lies niveaupassende Texte wiederholt und uebe Hauptaussage, Details und Schlussfolgerungen.",
      fr: "Lisez plusieurs fois des textes adaptes au niveau et travaillez idee generale, detail et inference.",
      uk: "Читайте тексти відповідного рівня повторно й практикуйте головну думку, деталі та висновки.",
    }),
    ielts: text("Connect your level work to IELTS-style vocabulary, grammar control, and timed reading habits.", {
      ar: "اربط عمل المستوى بمفردات IELTS ودقة القواعد وعادات القراءة المحددة بالوقت.",
      tr: "Seviye calismanizi IELTS tarzi kelime, gramer kontrolu ve zamanli okuma aliskanliklarina baglayin.",
      es: "Conecta el trabajo de nivel con vocabulario IELTS, control gramatical y lectura cronometrada.",
      it: "Collega il lavoro di livello a lessico IELTS, controllo grammaticale e lettura a tempo.",
      de: "Verbinde Niveauarbeit mit IELTS-Wortschatz, Grammatikpraezision und Lesen unter Zeitdruck.",
      fr: "Reliez le travail de niveau au vocabulaire IELTS, a la precision grammaticale et a la lecture chronometree.",
      uk: "Поєднайте роботу над рівнем із лексикою IELTS, граматичною точністю й читанням на час.",
    }),
    business: text("Practise workplace scenarios so accuracy becomes usable in meetings and interviews.", {
      ar: "تدرب على مواقف العمل حتى تصبح الدقة قابلة للاستخدام في الاجتماعات والمقابلات.",
      tr: "Dogruluk toplantilarda ve mulakatlarda kullanilabilir olsun diye is senaryolari calisin.",
      es: "Practica situaciones laborales para que la precision sirva en reuniones y entrevistas.",
      it: "Pratica scenari professionali per rendere l'accuratezza usabile in riunioni e colloqui.",
      de: "Uebe Arbeitsplatzszenarien, damit Genauigkeit in Meetings und Interviews nutzbar wird.",
      fr: "Pratiquez des situations professionnelles pour rendre la precision utilisable en reunion et entretien.",
      uk: "Практикуйте робочі ситуації, щоб точність працювала на зустрічах і співбесідах.",
    }),
  },
  skills: {
    vocabulary: text("Vocabulary", {
      ar: "المفردات",
      tr: "Kelime",
      es: "Vocabulario",
      it: "Vocabolario",
      de: "Wortschatz",
      fr: "Vocabulaire",
      uk: "Словник",
    }),
    grammar: text("Grammar", {
      ar: "القواعد",
      tr: "Gramer",
      es: "Gramatica",
      it: "Grammatica",
      de: "Grammatik",
      fr: "Grammaire",
      uk: "Граматика",
    }),
    reading: text("Reading", {
      ar: "القراءة",
      tr: "Okuma",
      es: "Lectura",
      it: "Lettura",
      de: "Lesen",
      fr: "Lecture",
      uk: "Читання",
    }),
  },
} as const;
